### ISSUE TITLE
代币信息及tpt捐赠哈希都提交了，一直没得到更新。

### ISSUE THREAD

**Issue by UniallPay** [TP-Lab/tokens#10081]
代币合约：
0x1FbE6902604b8cC3e35a3DB2f5d273Dbc8905636
哈希查询：
https://bscscan.com/tx/0x407a4779fb61e6a36212e3bf0760f9172134c026e4f6fa27d461a10804f9b731

交易哈希：
0x407a4779fb61e6a36212e3bf0760f9172134c026e4f6fa27d461a10804f9b731

**Comment by opera0001** [comment]
Sorry dear, an oversight in the review process led to the logo not being included successfully. It has now been added for you. Apologies for any inconvenience.
