### ISSUE TITLE
Add FTQ logo and info

### ISSUE THREAD

**Issue by FrameworkTech** [TP-Lab/tokens#10205]
Previously my ticket #10155 was closed and I received a reply from opera0001 that
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

We have since updated to a new smart contract and the code is open source
https://bscscan.com/address/0x800bbe68bb0514B3DA9773F9764099A269511c24#code

Here is the submitted hash:
https://bscscan.com/tx/0xbcd747ca079fdd37594a7f838d199dd1328c87e7c5a57b10acc606ddb4d2e768

**Comment by opera0001** [comment]
Done
