### ISSUE TITLE
Logo update 

### ISSUE THREAD

**Issue by Faisalali84** [TP-Lab/tokens#10242]

**Comment by opera0001** [comment]
If you need a logo update, you will need to provide me with some data.

**Comment by Faisalali84** [comment]
Contract address
0x8C36d650d923b73183b44fc072F4713681D86D40

Twitter https://x.com/wallStreetmemei


Telegram
https://t.me/officalwallstreetmeme

Logo https://wallstreetmemeinu.com/logo.jpg


My telegram I'd @williamking1

**Comment by opera0001** [comment]
The token does not have a logo, so if you need to add a logo, you will need to submit it through our tutorial.

https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info
