### ISSUE TITLE
PR info not show normally in TP wallet app

### ISSUE THREAD

**Issue by MrLiu163** [TP-Lab/tokens#10251]
Hi, admin, the PR has been merged for a long time, but the TP Wallet App information has not been updated.

[The PR](https://github.com/TP-Lab/tokens/pull/10071)
[Token Contract](https://etherscan.io/token/0xCc857F9A89C55DE54F3D56961DCd48231c1BDD67)

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/99cdccb1-6f95-4b01-b8ce-442527c0c63b)
The submitted logo has been successfully recorded, and its display is normal. Please double-check.

**Comment by MrLiu163** [comment]
Hi admin, the token name or symbol is not updated as in PR info, and the token detail intro info are not updated too.
![IMG_1898](https://github.com/TP-Lab/tokens/assets/20633918/3da3f1cf-15e3-4b4d-b69d-190122d8d346)
![IMG_1899](https://github.com/TP-Lab/tokens/assets/20633918/ed931959-4e4a-40db-bed4-78f5a3b91256)

**Comment by opera0001** [comment]
Sorry dear, this information is not automatically recorded.

**Comment by MrLiu163** [comment]
Hi, Admin, So how to update the information circled in red in the screenshot above in the TP wallet? This information will not be updated in the PR that has paid 50,000 TP?

**Comment by opera0001** [comment]
Dear, according to the rules we are currently following, the inclusion of token logos typically does not involve the inclusion of any additional information. Please understand. Thank you.
