### ISSUE TITLE
0xf3b185ab60128e4c08008fd90c3f1f01f4b78d50

### ISSUE THREAD

**Issue by autonit** [TP-Lab/tokens#10317]
Questions about the tokens, 0 xf3b185ab60128e4c08008fd90c3f1f01f4b78d50, because the proportion of the problem, with the original image after upload some deformation, request a change  

![be8c36a42d06624c30cdd5cb4f48899](https://github.com/TP-Lab/tokens/assets/158179893/92ce23a7-f23e-46e0-a599-f93d8bec75ed)

**Comment by opera0001** [comment]
Done
