### ISSUE TITLE
Explanation about the GitHub account being banned.

### ISSUE THREAD

**Issue by LuiMadeline** [TP-Lab/tokens#10382]
The order I submitted in the past is: https://github.com/TP-Lab/tokens/pull/10373. It was submitted with a completely new account, but GitHub mistakenly banned my new account, causing my submission to not be included in the review process at the scheduled time. Therefore, I raised an issue, hoping for a prompt resolution. Thank you very much. My new order is: https://github.com/TP-Lab/tokens/pull/10381.

**Comment by opera0001** [comment]
Done
