### ISSUE TITLE
Submit BRC20 Token Image

### ISSUE THREAD

**Issue by talha13** [TP-Lab/tokens#10447]
Hi

How can i submit brc20 token icon? I don't find any specific directory which allow me to upload brc20 icon on how to submit link below

https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/e7ee4713-9e02-456a-8ab7-9961aa649c08)


Dear, you can submit within this directory.

**Comment by talha13** [comment]
Thanks a lot
