### ISSUE TITLE
Uploads are disabled.

### ISSUE THREAD

**Issue by NEOFANTASY7** [TP-Lab/tokens#10457]
Uploads are disabled.
File uploads require push access to this repository.

How should I change the permissions and submit them?

**Comment by opera0001** [comment]
Dear, you need to fork first before you can select the directory for submitting tokens and upload. Please refer to the instructions in the tutorial.

CN：https://help.tokenpocket.pro/cn/developer/submit-logo

EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info
