### ISSUE TITLE
about logo 关于logo

### ISSUE THREAD

**Issue by testdasdsafe** [TP-Lab/tokens#10483]
Add burnatm logo and info.json #10476

由于无法fork,也不可用upload file 我是通过creat new file 来提交的logo文件夹,提交后的连接如下:
https://github.com/TP-Lab/tokens/pull/10476
因为时间已经超过3天,而且logo并没有更新,我想请问一下这样的方式是否正确.

Since it is impossible to fork and upload file is not available, I submitted the logo folder through creat new file. The connection after submission is as follows:
https://github.com/TP-Lab/tokens/pull/10476
Because it has been more than 3 days and the logo has not been updated, I would like to ask if this method is correct.

**Comment by opera0001** [comment]
Once you have registered and logged in to GitHub, you can open https://github.com/TP-Lab/tokens, then click on "fork", and choose the blockchain directory you want to submit, such as the bsc directory. After uploading the folder, you can complete the operation.

**Comment by testdasdsafe** [comment]
I made a new one. I'm very sorry. Could you please take a look?

https://github.com/TP-Lab/tokens/pull/10484

**Comment by opera0001** [comment]
The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

**Comment by testdasdsafe** [comment]
> The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

thanks a lot

**Comment by testdasdsafe** [comment]
> The order application has been received, please wait patiently for the review. Do not believe any unofficial messages, and protect yourself from being scammed.

Hello administrator, it has been 5-7 days. I would like to ask why I still don’t see the logo on the wallet.
