### ISSUE TITLE
#10498 The new address has been adjusted and completed

### ISSUE THREAD

**Issue by ade23asd** [TP-Lab/tokens#10526]
Contract address:：0xD5337315fA408afEEA9c660c33c8090Fc4c98f09
![logo](https://github.com/TP-Lab/tokens/assets/166147763/7c2fcd53-ee9e-40c6-bac4-8ce02017cbf7)

**Comment by ade23asd** [comment]
#10498  this historical submission

**Comment by opera0001** [comment]
Done

**Comment by ade23asd** [comment]
Has it been merged? Why can't I view it in the BSC directory
