### ISSUE TITLE
Update  logo

### ISSUE THREAD

**Issue by Dictators** [TP-Lab/tokens#10543]
Our application for logo replacement has been submitted, but the old version of the logo is still on the application. Could you please help us update it
[https://github.com/TP-Lab/tokens/pull/10532](url)

**Comment by Dictators** [comment]
The old logo is still displayed


![image](https://github.com/TP-Lab/tokens/assets/24631857/7483726c-b944-4add-aa60-37ef6ceaf2bb)

**Comment by Dictators** [comment]
Anyone can help me ?

**Comment by Dictators** [comment]
@opera0001  Excuse me

**Comment by opera0001** [comment]
Sorry, dear, it has been updated.

**Comment by Dictators** [comment]
Yes, i have,thank  you
