### ISSUE TITLE
updata  logo

### ISSUE THREAD

**Issue by Dictators** [TP-Lab/tokens#10562]
Hello, can you help me update the logo and address is  0x4d0528598f916fd1d8dc80e5f54a8feedcfd4b18
Just donated it last week

![logo](https://github.com/TP-Lab/tokens/assets/24631857/c2d57e58-b1dc-49aa-a180-4aa3322a18d0)

**Comment by opera0001** [comment]
Dear, the logo you recently submitted is exactly the same as the one submitted last time. Please review it again.

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/a9a67080-2886-4d2c-8a1a-fb3f1e5e17a2)
