### ISSUE TITLE
ADD SEED

### ISSUE THREAD

**Issue by babyface001** [TP-Lab/tokens#10593]
https://github.com/TP-Lab/tokens/pull/10552

token is open sourced

https://arbiscan.io/address/0xcC37D81d0e63c4733C5B0176422d9407714606d9#code

**Comment by amu2025** [comment]
I don't want to apply for TP logo. Can TPT be returned?

**Comment by opera0001** [comment]
> I don't want to apply for TP logo. Can TPT be returned?

The payment with TPT is considered a donation, as detailed in the tutorial, so it's important to carefully consider before proceeding. The token you submitted seems to have some issues. Although it's open-source, there isn't much additional information available. Please check if the token issuance code is correct. While TPT donations cannot be refunded, as long as the submitted logo hasn't been included yet, you can continue to use this TPT.

**Comment by babyface001** [comment]
@opera0001 what additional information needed?
