### ISSUE TITLE
Incorrect Report "It's marked as phishing or scaming token "

### ISSUE THREAD

**Issue by akalper** [TP-Lab/tokens#10713]
Although there is no security, spam or phishing problem with our token, it is shown as "It's marked as phishing or scaming token" on the token security page. Such data is not available neither on GoPlus nor anywhere else. On what basis was this marking made? I would ask you to do the necessary.

Our Token Contract: 0xDF0c4950A33F04C227120E84d1A052564c4F62fD

TokenPocket Wrong Report
https://tokensecurity.tokenpocket.pro/#/?address=0xDF0c4950A33F04C227120E84d1A052564c4F62fD&ns=ethereum&chain_id=56&blockchain_id=12

GoPlus Report
https://gopluslabs.io/token-security/56/0xDF0c4950A33F04C227120E84d1A052564c4F62fD

Kind Regards

**Comment by opera0001** [comment]
Dear user,

The token detection results in TokenPocket come from our partner, GoPlus. If you have any questions about the detection content, you can try to communicate with their team through their official website: [https://gopluslabs.io](https://gopluslabs.io) to resolve the issue. If everything is fine, they will update the data, and the data in TokenPocket will be automatically updated as well.

**Comment by akalper** [comment]
I see that the data comes through GoPlus, but there is no such risk notification on GoPlus' own report page. You can also see it by clicking the link below. Additionally, I am sending a screenshot. I am also discussing this issue with the GoPlus team.

Go Plus Report
https://gopluslabs.io/token-security/56/0xdf0c4950a33f04c227120e84d1a052564c4f62fd

ScreenShoot
https://prnt.sc/sdSN-RfCq9DA

**Comment by akalper** [comment]
We just talked to GoPlus via Official Telegram @Goplusservice . They confirmed that there was no such marking. So this problem is caused by you. You can access the screenshot of this conversation from the link below.

![goplus-screen02](https://github.com/TP-Lab/tokens/assets/111438392/4e570c72-6048-4300-82f5-39c349d2508b)
![goplus-screen01](https://github.com/TP-Lab/tokens/assets/111438392/cc86aff4-e49b-42ff-bea1-ee28888884dc)

**Comment by opera0001** [comment]
Please update the detection tool results in TokenPocket. Currently, everything is normal because the data in TokenPocket only updates after goplus is updated.

**Comment by akalper** [comment]
"Please update the detection tool results in TokenPocket. Currently, everything is normal"

Did you write that everything seems normal? Your data still appears to be incorrect. As I said before and talked to the GoPlus team, GoPlus does not make such a marking. But it still appears checked in TokenPocket. I'm adding screenshots below. Please explain this to me. While there is no such marking and risk notification on GoPlus' own page, why do you still see it?

<img width="1323" alt="Cursor_and__XCL_Token_Security" src="https://github.com/TP-Lab/tokens/assets/111438392/e416dfcf-dbdb-4e7b-b101-21535676ad14">
<img width="1335" alt="Security_Detection" src="https://github.com/TP-Lab/tokens/assets/111438392/1e4b4e03-db32-440d-8fe4-848c8f444d4d">
