### ISSUE TITLE
Incorrect Report "It's marked as phishing or scaming token " #10713 - Not Solved Problem

### ISSUE THREAD

**Issue by akalper** [TP-Lab/tokens#10730]
"Please update the detection tool results in TokenPocket. Currently, everything is normal"

Did you write that everything seems normal? Your data still appears to be incorrect. As I said before and talked to the GoPlus team, GoPlus does not make such a marking. But it still appears checked in TokenPocket. I'm adding screenshots below. Please explain this to me. While there is no such marking and risk notification on GoPlus' own page, why do you still see it?

<img width="1323" alt="Cursor_and__XCL_Token_Security" src="https://github.com/TP-Lab/tokens/assets/111438392/fe952d79-de9c-4ccd-b77b-106b24de2632">
<img width="1335" alt="Security_Detection" src="https://github.com/TP-Lab/tokens/assets/111438392/971ab434-7126-458b-b581-3f9aebed6249">

**Comment by opera0001** [comment]
https://tokensecurity.tokenpocket.pro/?utm_source=tokenpocket#/?address=%200xDF0c4950A33F04C227120E84d1A052564c4F62fD&ns=ethereum&chain_id=56&blockchain_id=12

![image](https://github.com/TP-Lab/tokens/assets/99245006/dba5e7e2-1f41-4f53-b3e7-7bab0f91e6f4)

Dear user,

When I replied to you last time, the risk warning had already disappeared. Please try using a different browser or clearing your cache to check the results.

**Comment by akalper** [comment]
We tried everything, we tried emptying all the caches from different computers and different IPs. We noticed this. The link you sent is different from the link on the page.

In the link you sent, there is a prefix like "%20" at the beginning of the contract number, I share it in the screenshot.

_**The link you sent (There is no error here.)**_
https://tokensecurity.tokenpocket.pro/?utm_source=tokenpocket#/?address=%200xDF0c4950A33F04C227120E84d1A052564c4F62fD&ns=ethereum&chain_id=56&blockchain_id=12

--------------------------------------------------------------------------

**_The link we receive as a user. (The error is still marked here.)_**
https://tokensecurity.tokenpocket.pro/?utm_source=tokenpocket#/?address=0xDF0c4950A33F04C227120E84d1A052564c4F62fD&ns=ethereum&chain_id=56&blockchain_id=12

![Document1](https://github.com/TP-Lab/tokens/assets/111438392/413d3fa3-6772-4807-aa65-a039a5dcfc31)

Additionally, this problem continues in TP Wallet. I am sending the screenshot of it. In short, the link you sent me is not the same as the link from which the data was received. I think there is another problem here.

![IMG_9537](https://github.com/TP-Lab/tokens/assets/111438392/ce4ab0dd-8448-4324-94c0-3a64649bde44)
![IMG_9535](https://github.com/TP-Lab/tokens/assets/111438392/1794a65c-4dff-4c8e-9040-5628d0b24d26)
![IMG_9534](https://github.com/TP-Lab/tokens/assets/111438392/da1fdef6-c948-47a1-8423-768f15c0c4e6)

Kind Regards

**Comment by opera0001** [comment]
Hey, sorry dear, I didn't notice that this token had been flagged with a risk warning. The alert you saw was due to this status setting. Now it is completely normal. Please check it again.

**Comment by akalper** [comment]
Yes, great, the warning problem seems to be gone now. However, the token logo and information still did not return normally. With this warning, the logo, token descriptions and links disappeared. Could you check them, please?

Previously pushed Token Information
https://github.com/TP-Lab/tokens/tree/fb28a705dbd12a57fc506e6327a2691096ad197a/bsc/0xDF0c4950A33F04C227120E84d1A052564c4F62fD

![token-xcl-premiew-missing-logo-and-links](https://github.com/TP-Lab/tokens/assets/111438392/50095317-dd39-4552-896a-bfdeb8585bbb)
![transitswap-missing logo](https://github.com/TP-Lab/tokens/assets/111438392/d977b49e-85d4-4170-b709-bca60ca23bb4)


Once we solve this problem, there is no problem.

**Comment by opera0001** [comment]
Has this token's logo appeared before? How was it submitted? If it was submitted through GitHub, please send me the submitted order for verification. Thank you.

**Comment by opera0001** [comment]
DONE
