### ISSUE TITLE
 Now I want to issue a new token to replace this failed token. May I ask if the fee that has been submitted can be reused

### ISSUE THREAD

**Issue by RRR1024** [TP-Lab/tokens#10741]
![08309925232f94c457c6f29d561d712](https://github.com/TP-Lab/tokens/assets/153991905/d8910658-ab47-4116-8af6-c3c0a786c4e8)

**Comment by opera0001** [comment]
Yes, dear, the submitted order has not been recorded, so the provided hash value link can continue to be used. Please resubmit the order.

**Comment by RRR1024** [comment]
thx！！
