### ISSUE TITLE
Removed old TRIAS logo

### ISSUE THREAD

**Issue by dallejohn** [TP-Lab/tokens#10809]
Hello, dear TP Wallet：
The Trias team recently issued a new TRIAS to resolve the error in the total amount of the old TRIAS issuance.
Now Gate, MEXC, and Bitget have completed the TRIAS token exchange. Apply to change the TRIAS token displayed in the TP wallet to the new TRIAS

TRIAS new contract address
0x184cff0e719826b966025f93e05d8c8b0a79b3f9

TRIAS old contract address
0xa4838122c683f732289805fc3c207febd55babdd

Project official announcement
https://x.com/triaslab/status/1806606241957073394

Gate.io Supports Trias (TRIAS) Token Migration
https://www.gate.io/announcements/article/37766

MEXC Will Support the Trias (TRIAS) Contract Swap
https://www.mexc.com/support/articles/17827791517201

Bitget Will Support the Trias (TRIAS) Contract Swap
https://www.bitget.com/support/articles/12560603812558

**Comment by opera0001** [comment]
Done

**Comment by dallejohn** [comment]
> 完毕
Hello, dear TP wallet, currently in TP wallet - add tokens, search directly for TRIAS, and the old TRIAS information is still displayed

![1](https://github.com/user-attachments/assets/656efb66-6be0-490c-bfb6-581b46da3680)
![2](https://github.com/user-attachments/assets/a3cf2718-2c89-4660-a471-3d125cfaee41)
