### ISSUE TITLE
Removed old SVT logo

### ISSUE THREAD

**Issue by skonw** [TP-Lab/tokens#10820]
Hello, dear TP Wallet： The Smart Wallet team recently issued a new SVT to resolve the error in the total amount of the old SVT issuance.  Apply to change the SVT token displayed in the TP wallet to the new SVT
SVT new contract address GmsB74pKYXKAFXvPcMCwy6gQDMGXJaHoR5w6BbneGxFq
SVT old contract address C8kPRR4U9Gzu4mgHgVyDmdvSCHYjSz2k7h2FWKWdJaBo

**Comment by skonw** [comment]
The new contract address has been resubmitted，https://github.com/TP-Lab/tokens/pull/10818
I only hope to remove the old logo and keep other information

**Comment by opera0001** [comment]
Dear, I have removed the logo displayed on the old contract address for you. The new logo you submitted has also passed the review and will be updated within the next two days. Please be patient.
