### ISSUE TITLE
wdum "Please submit the complete file" ?

### ISSUE THREAD

**Issue by ImUrFuture** [TP-Lab/tokens#1087]
Please submit the complete file.

_Originally posted by @zhujiayu03 in https://github.com/TP-Lab/tokens/issues/958#issuecomment-875399830_
我已经提交了头像logo和info，请问我还缺少什么文件？
我已经提交了新的pull request #1086，请尽快审核一下
先前的pull request pr#958

**Comment by ImUrFuture** [comment]
已重新提交文件，感谢提醒。麻烦尽快帮我审核，不想再重新排队了，谢谢。

**Comment by zhujiayu03** [comment]
请将文件提交至相对应的matic文件夹

**Comment by ImUrFuture** [comment]
已经重新提交到matic文件夹 麻烦尽快处理



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Thu,Jul 8,2021 10:52 AM
To: TP-Lab/tokens ***@***.***&gt;
Cc: ImUrFuture ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] wdum "Please submit the complete file" ? (#1087)





 
Closed #1087.

**Comment by ImUrFuture** [comment]
你好，我已经重新提交了 #1121。
之前的pr#958 #1086。
麻烦尽快审核一下谢谢。很着急。已经等了很多天了，万分感谢


Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Thu,Jul 8,2021 10:52 AM
To: TP-Lab/tokens ***@***.***&gt;
Cc: ImUrFuture ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] wdum "Please submit the complete file" ? (#1087)





 
请将文件提交至相对应的matic文件夹

**Comment by ImUrFuture** [comment]
Dear mr.zhujiayu
Pls merge my commit#1121 ASAP.
Pr#958 #1086
哥哥求你了快点帮我审核吧万分感谢🙏


Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: zhujiayu03 ***@***.***&gt;
Date: Thu,Jul 8,2021 10:52 AM
To: TP-Lab/tokens ***@***.***&gt;
Cc: ImUrFuture ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [TP-Lab/tokens] wdum "Please submit the complete file" ? (#1087)





 
请将文件提交至相对应的matic文件夹
