### ISSUE TITLE
已重新提交Add OKC logo and info #1083

### ISSUE THREAD

**Issue by zhangshoushu** [TP-Lab/tokens#1091]
已经重新提交了，非常感谢您的提醒，可以帮忙审核吗？新的提交：Add OKC logo and info #1083

**Comment by zhujiayu03** [comment]
请耐心等待

**Comment by zhangshoushu** [comment]
> 请耐心等待

谢谢您，如果可以提前，我们将万分感谢，这是因我们的错误导致了更多的等待，重新更正错误还望可以提前安排。非常非常感谢您！
