### ISSUE TITLE
0x7045e3f0456DaAD3176e1B51cbd94e86B44CA99D lOGO调整一下

### ISSUE THREAD

**Issue by Sungood520520** [TP-Lab/tokens#10974]
您好，把这个合约的lOGO调整下，原来的没有铺满,谢谢！
0x7045e3f0456DaAD3176e1B51cbd94e86B44CA99D
![logo](https://github.com/user-attachments/assets/96418221-4f58-4e52-b08b-48908ce19b49)

**Comment by opera0001** [comment]
Done
