### ISSUE TITLE
Update FIST avatar

### ISSUE THREAD

**Issue by ziweiwest** [TP-Lab/tokens#11012]
TPT：0xff30b5c887a5335bd15d39c0830266979050056434ad9b27bba7b4e528122b9c
BNB：0xcf4cfe03f592b4d158ad8fd3cfc71c630592d3b1c5bc780b0261f90a1b960f16

**Comment by ziweiwest** [comment]
[info.json.txt](https://github.com/user-attachments/files/17179958/info.json.txt)
![logo](https://github.com/user-attachments/assets/3adc51e1-87eb-48f3-9b72-36427147f971)

**Comment by opera0001** [comment]
Done
