### ISSUE TITLE
先前pr#958 #1086 添加PolyBabyDoge的logo

### ISSUE THREAD

**Issue by ImUrFuture** [TP-Lab/tokens#1123]
#1121已经重新提交至matic文件夹，请尽快处理。
ps：我之前提交的时候根本没有创建matic的文件夹啊，之后你们才创建的，现在帮我加急处理一下无可厚非吧。

**Comment by ImUrFuture** [comment]
zhujiayu哥哥求求你了快点帮我审核一下吧。等了好几天了都。万分感谢！我以后只用tp钱包 tpt to the moon！

**Comment by ImUrFuture** [comment]
@zhujiayu03

**Comment by zhujiayu03** [comment]
已添加。
