### ISSUE TITLE
10多天了，修改了三次，能不能帮忙提前审核一下好吗？

### ISSUE THREAD

**Issue by zhangshoushu** [TP-Lab/tokens#1282]
第一次400多编号，每二次是1083 ，还是没过，没提交到heco上。太大意了。这次是提交了，能帮我们先处理一下吗？非常感谢！！
https://github.com/TP-Lab/tokens/pull/1281

**Comment by zhujiayu03** [comment]
请将文件夹提交至heco文件夹。
