### ISSUE TITLE
原https://github.com/TP-Lab/tokens/pull/1281 已经重新使用新账号提交，请帮忙！

### ISSUE THREAD

**Issue by zhangshoushu** [TP-Lab/tokens#1338]
还望能得到照顾，已经17天了，中途一直因失误未正确提交到HECO。现在我们另一个账号已重新提交（原来的编号1281）。最新提交的是：https://github.com/TP-Lab/tokens/pull/1319
还望审核人员帮忙审核。非常非常感谢！

**Comment by zhujiayu03** [comment]
已审核
