### ISSUE TITLE
麻烦处理一下#1503 之前#1335被关闭了 已重新提交文件 麻烦尽快审核一下 谢谢

### ISSUE THREAD

**Issue by ImUrFuture** [TP-Lab/tokens#1504]
更新一下logo标志
交易哈希链接：https://bscscan.com/tx/0x53f18bff827045067ac936017acebd6f2ad562ebd2c55c98136363bf01e67641

**Comment by ImUrFuture** [comment]
@zhujiayu03

**Comment by zhujiayu03** [comment]
工作日5天内将完成审核，感谢您的耐心等待。
