### ISSUE TITLE
显示已合并，但是钱包内还是不显示logo呢

### ISSUE THREAD

**Issue by wulala0714** [TP-Lab/tokens#1557]
币名：GOOFY     #1388
合约地址：0x3A64aD8FFd6f1be6884Ea7f17a09c8F7B434A546

**Comment by zhujiayu03** [comment]
请刷新后再次查看。

**Comment by wulala0714** [comment]
logo加错地方了，GOOFY的合约地址是0x3A64aD8FFd6f1be6884Ea7f17a09c8F7B434A546，能给换到这个合约地址上吗
