### ISSUE TITLE
#1733 经查文件名正确，若有其他问题麻烦指出，谢谢

### ISSUE THREAD

**Issue by msmoon520** [TP-Lab/tokens#1894]
#1733 经查是正确使用合约地址作为文件名的，请注意查看，谢谢！如下图：
![image](https://user-images.githubusercontent.com/87417286/127416571-0ba79ae1-2ddc-4f80-9be7-b28b0914b8a8.png)
![image](https://user-images.githubusercontent.com/87417286/127416629-2455e6f8-4bbd-4b00-8f4f-14aa2e36b12a.png)
其他问题还请指出，辛苦您了，可果没有错请帮忙审核。

**Comment by zhujiayu03** [comment]
checksum合约地址是指包含大写和小写的合约地址，请参考教程重新提交。
