### ISSUE TITLE
已合并，但是文件却没有被合并进去

### ISSUE THREAD

**Issue by bk1d** [TP-Lab/tokens#2261]
我提交过下面两个信息，都是按要求转账、填写信息。但是在合并后，并没有文件被添加进去。App 也不显示图标。
是我提交的有问题吗？

https://github.com/TP-Lab/tokens/pull/2226
https://github.com/TP-Lab/tokens/pull/2189

**Comment by zhujiayu03** [comment]
CPIE logo已经添加，请刷新后查看。

**Comment by bk1d** [comment]
我这两次提交的是下面这两个BSC合约，并不是CPIE。

0x154ECeB42679ac155EeF18820dE2Be75699263A8
0xEB35aCBD23CF9D1C13D276815B9969eFfC5c878f
