### ISSUE TITLE
已经交易很多次，价格还是没显示

### ISSUE THREAD

**Issue by haomastudio123** [TP-Lab/tokens#2466]

**Comment by okoFlying** [comment]
这跟TP钱包没关系、我知道如何解决  联系我V：udianxian

**Comment by GMclub** [comment]
这个和TP没关系，价格高容易显示

**Comment by guchengzhi123** [comment]
> 之前发帖回复我们说需要多交易几次，
> 币安链的代币，在薄饼已经交易很多次，价格还是没显示。
> 
> ・0xFc6174FED0956FAAcC6204c01A67F10D4d18494D
> 
> 在火币钱包里面都有价格显示，能麻烦看看TP钱包怎么不显示价格吗？感谢

我们马上提交
