### ISSUE TITLE
添加信息和徽标

### ISSUE THREAD

**Issue by alw123456** [TP-Lab/tokens#2625]
“名称”： “Unirealchain”，
“网站”： “ - ”，
“描述”： “Unirealchain”，
“资源管理器”： “https://hecoinfo.com/address/0x5CFA09048973d32a24a83c2EBB9846F1b8B6200C ”，
“类型”： “ HRC-20”，
“符号”：“UNR”，
“小数”：18，
“状态”：“活动”，
“id”：“0x5CFA09048973d32a24a83c2EBB9846F1b8B6200C”
}
![unirealchain](https://user-images.githubusercontent.com/84399291/129590961-610f07fa-0685-4ef1-aef4-c6b8338f585d.png)

**Comment by alw123456** [comment]
> “名称”： “Unirealchain”，
> “网站”： “ - ”，
> “描述”： “Unirealchain”，
> “资源管理器”： “ https://hecoinfo.com/address/0x5CFA09048973d32a24a83c2EBB9846F1b8B6200C ”，RC
> “类型”： “ H -20”，
> “符号”：“UNR”，
> “小数”：18，
> “状态”：“活动”，
> “id”：“0x5CFA09048973d32a24a83c2EBB9846F1b8B6200C”
> }
> ![单链](https://user-images.githubusercontent.com/84399291/129590961-610f07fa-0685-4ef1-aef4-c6b8338f585d.png)

**Comment by ASSACC** [comment]
{
 "name": "ASSACC Token",
 "website": "https://www.assapay.com/",
 "description": "I am using it in online e-commerce and I want to use it as a payment method in distribution.",
 "explorer": "https://www.eosx.io/account/friendsnow12",
 "type": "EOS",
 "symbol": "A",
 "decimals": 3,
 "status": "active",
 "id": "friendsnow12"
}
![logo png](https://user-images.githubusercontent.com/90316168/132655607-13bcdf53-3b80-4e94-8c3f-6857e178ed83.png)
