### ISSUE TITLE
fail to pass.

### ISSUE THREAD

**Issue by xiaoxiangzi360** [TP-Lab/tokens#2825]
fail to pass.

_Originally posted by @giki0318 in https://github.com/TP-Lab/tokens/issues/2656#issuecomment-903769894_

**Comment by xiaoxiangzi360** [comment]
哪里不能通过，请告知，只说通过失败，我1000个TPT也转了，格式也没错

**Comment by xiaoxiangzi360** [comment]
已经提交三四次了，真的累了，也不说哪里错了

**Comment by tebcommunity** [comment]
> 已经提交三四次了，真的累了，也不说哪里错了
合约地址 要用文档提示的那种格式

**Comment by xiaoxiangzi360** [comment]
放弃
