### ISSUE TITLE
mcu提交logo 提交多次，logo未显示，但是显示已经添加

### ISSUE THREAD

**Issue by lgkj123** [TP-Lab/tokens#2909]
bsc链的代币
mcu
智能合约地址：0x65Fc381dF3D6d84De6f4A39705696d3aEf233245
转tpt链接：https://bscscan.com/tx/0xda827032c5bc0b2a7a0d4584b7ef1c21a3499bdf06b79ec20a3e9019a36ad6bd
logo：
![c6cece26fc1a2486c86e8b777dc70b8](https://user-images.githubusercontent.com/87652972/130773863-d8fd003e-e3b8-4d70-a463-b753df35a5e0.png)

现在就想问问，能不能给显示出logo来，我们已经一个月了，提交了五六次了，每次都是显示通过，但是logo显示不出来，就是想请问工程师哪里不对，是不是第一次提交的logo格式不对，后面提交的logo替换不掉

**Comment by jackbob123** [comment]
能不能看看啥情况啊

**Comment by lgkj123** [comment]
#3035 已经再次提交了下，有时间麻烦处理下，谢谢！

**Comment by oko-token3** [comment]
> BSC链的代币
> MCU
> 智能合约地址：0x65Fc381dF3D6d84De6f4A39705696d3aEf233245
> 转TPT链接：https://bscscan.com/tx/0xda827032c5bc0b2a7a0d4584b7ef1c21a3499bdf06b79ec20a3e9019a36ad6bd
> 标志：
> ![c6cece26fc1a2486c86e8b777dc70b8](https://user-images.githubusercontent.com/87652972/130773863-d8fd003e-e3b8-4d70-a463-b753df35a5e0.png)
> 
> 现在就想问问，能不能给显示出logo来，我们已经知道了，提交了五六次了，每次都显示通过，但是logo显示不出来，想问问工程师哪里不对，是不是第一次提交的logo格式不对，下一次提交的logo替换不掉

你这个图标格式不正确吧  要求的是   256*256 px  的

**Comment by lgkj123** [comment]
已解决
