### ISSUE TITLE
BSC - TPT - 0x422603D04D5960D66c6f59dD95e26f9DcF3607A1 -

### ISSUE THREAD

**Issue by Binahunter** [TP-Lab/tokens#3395]
BSC - TPT - 0x422603D04D5960D66c6f59dD95e26f9DcF3607A1 -
https：//bscscan.com/tx/0xb21b9e6452b8d27bdc83efcdad2c3a81f015b075f667d6242624a40e1ffb41af

**Comment by opera0001** [comment]
No info.json file submission
