### ISSUE TITLE
Please remove the LOGO and the info of the old abandoned token(abandoned: 0xa123ab52a32267dc357b7599739d3c6caf856fe4).

### ISSUE THREAD

**Issue by Satoshiisgod** [TP-Lab/tokens#3541]
Hello TokenPocket team,

Please remove the LOGO and the info of the old token(abandoned: 0xa123ab52a32267dc357b7599739d3c6caf856fe4).

The AIR token has migrated to new contract address(Active: 0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53).

Here is the Immigration announcement(Community ):
https://aircoin.community/t/announcement-clarification-of-the-air-migration-att20210907-009/304

Thanks again, and we wish you a great day.

Best Regards,

Yolo Sana

**Comment by opera0001** [comment]
Done
