### ISSUE TITLE
Lake

### ISSUE THREAD

**Issue by zjp025115** [TP-Lab/tokens#3635]

**Comment by zjp025115** [comment]
We hope to build a global Lakers fan community in the future. In this community, NBA Lakers fan tokens can be used to vote, buy game tickets, video memberships, souvenirs and live broadcast rewards, etc. The Lakers family is a loving family. We can also donate  fan tokens to help children in poverty-stricken areas regain their basketball dreams.

**Comment by opera0001** [comment]
Okay, go, go, go
