### ISSUE TITLE
3000TPT has been transferred, why not?

### ISSUE THREAD

**Issue by scsp1064** [TP-Lab/tokens#3848]
Not enough 3000TPT for the first time
The second time is just to explain the first problem, and then you don't see it?
This address is paid 3000. Don't you look at it?
Almost a month.

https://github.com/TP-Lab/tokens/pull/3745

https://bscscan.com/tx/0x910d9ecf333381b27e8f72939598442463cfc6aa260a601d21df042193f8f2ff
https://bscscan.com/tx/0x55f43c056fc1b9a3f0a9f006bfdd07b667e3df51a170efdabb66adbccf904a6c

**Comment by opera0001** [comment]
The token logo has been added.
