### ISSUE TITLE
#3794  could speed up the information update？

### ISSUE THREAD

**Issue by NewOriginToken** [TP-Lab/tokens#3852]
信息已经提交，tpt转账也转了，请问什么时候可以看到图标呢？
https://bscscan.com/tx/0x91ad4276ec3f757e0dd3fc8bca6ae853f29aad38b5fd8b60e8642bdaab2fa658

**Comment by NewOriginToken** [comment]
how long that logo will show?
could you tell me the time, ok?

**Comment by opera0001** [comment]
1. The contractual authority has not been abandoned and there are risks
2. It has the right to issue additional shares and has risks
