### ISSUE TITLE
怎么查看logo上传被拒绝没

### ISSUE THREAD

**Issue by shaboshi** [TP-Lab/tokens#4118]
怎么查看logo上传被拒绝没

**Comment by heipacker** [comment]
被close掉？

**Comment by nenrgycoin** [comment]
What number?

**Comment by xiangge5168** [comment]
求助，我怎么找到上转LOGO和资料窗口，谢谢

**Comment by nenrgycoin** [comment]
> 求助,我怎么找到上转标志；徽标和资料窗口,谢谢
Direct inquiry by number

**Comment by shaboshi** [comment]
你把你上传的 资料发来 ，我给你查看。我教是要收费的。
















在 2021-11-22 09:53:54，"祥" ***@***.***> 写道：

求助，我怎么找到上转LOGO和资料窗口，谢谢

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
