### ISSUE TITLE
Add KOALA logo

### ISSUE THREAD

**Issue by Koalabear2** [TP-Lab/tokens#4167]
Pleaase add koala logo(https://koabear.net)

**Comment by Koalabear2** [comment]
- @@ -0,0 +1,13 @@
{
"name": "KOALABEAR",
"website": "HTTPS://KOABEAR.NET",
"description": "BSC TOKEN",
"explorer": "https://bscscan.com/tokenupdate/0xA1217C0cce65A37E77cF43Af277c0B29D808652c",
"type": "BSC",
"symbol": "KOALA",
"decimals": 9,
"status": "active",
"id": "0xA1217C0cce65A37E77cF43Af277c0B29D808652c"
}
0 comments on commit cd3cb66

**Comment by opera0001** [comment]
Token logo has been added.

**Comment by Koalabear2** [comment]
it is still not added... kindly recheck and added please
