### ISSUE TITLE
Deeper Logo无法正确显示

### ISSUE THREAD

**Issue by AmadeusGB** [TP-Lab/tokens#4309]
我们提交过2次PR，其Logo已正确提交，但我们检查TP中的Deeper Logo时，发现无法正确显示。

第一次：https://github.com/TP-Lab/tokens/pull/3730  （10月28日）

第二次：https://github.com/TP-Lab/tokens/pull/4182   （4天前）

官方合并PR记录：https://github.com/TP-Lab/tokens/blob/master/eth/0xf3AE5d769e153Ef72b4e3591aC004E89F48107a1/logo.png

官方邮件回复：让我们再打TPT，这是否不太合适？请问何时能够正确显示Logo？

![deeper缺少logo](https://user-images.githubusercontent.com/25835280/144021093-41de02d3-f1bf-4aca-a228-b4b970014b3a.png)

**Comment by AmadeusGB** [comment]
@zhujiayu03

**Comment by sammvio** [comment]
请更新到最新版本
