### ISSUE TITLE
 Please review #4266 

### ISSUE THREAD

**Issue by DOD195450508** [TP-Lab/tokens#4331]
Add DOD and logo 

https://bscscan.com/tx/0x2908603568df53f6556055aca6cf2e8d79f436c574bc2220987451e5f35b2c27

https://bscscan.com/tx/0x243ed9f89326a9e76e1cdfac9305a56dab65c85b6d5392191a6deda63c84a05c

**Comment by opera0001** [comment]
1. The submitted web address cannot be opened
2. Administrator privileges were not waived
3. Higher buying and selling rates
Please re submit the logo application after adjustment or optimization. Thank you for your support for tokenpocket.
