### ISSUE TITLE
ADD AIR LOGO and INFO

### ISSUE THREAD

**Issue by Satoshiisgod** [TP-Lab/tokens#4522]
https://github.com/TP-Lab/tokens/pull/4521

BSC - AIR - 0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53 - https://bscscan.com/tx/0x61854586addb0847f9ac72a7ad4ef267a11cc8faf79f5615d01cfd106cea3e36

**Comment by Satoshiisgod** [comment]
AIR info is already merged on Github, but the LOGO is not displayed in the wallet APP.

So I resubmitted a new Pull Request and donated another 3000 TPT.

Here is the AIR info in the official Repo:

 https://github.com/TP-Lab/tokens/tree/master/bsc/0xd8a2aE43Fd061d24acd538e3866Ffc2c05151b53

**Comment by giki0318** [comment]
fixed
