### ISSUE TITLE
Please donate 3000 TPT as required and submit the transfer link on [Commit changes].

### ISSUE THREAD

**Issue by P2Exyz** [TP-Lab/tokens#4577]
PLS CHECK

BSC-P2E-0x7f9C20c4C09c32478AE10A7543E5199C2F53691d-https://bscscan.com/tx/0x15e7e3d59b0a1a70977f60027fd733d46b86268c34fc5d0c3d9e76fd3665881a

轉bnb鏈接-https://bscscan.com/tx/0x2043939864abccf6ce7a90cf93059f8baac3f9248ae3c579d17ee93166183559

**Comment by giki0318** [comment]
What's your PR number?

**Comment by pmmt** [comment]
0x0eabed5419c972c1de80895170b7ce5d1a067c041ce37cab0b1ac9ef07e7c6b5

**Comment by opera0001** [comment]
What's your PR number?

**Comment by EXPERTDOGE** [comment]
0xafeb208b41fbca32035b00d1e6318f1078d0a712e46eecb101db8073164bf32f

**Comment by dragonmoon001** [comment]
#4577
BSC-P2E-0x7f9C20c4C09c32478AE10A7543E5199C2F53691d-https://bscscan.com/tx/0x15e7e3d59b0a1a70977f60027fd733d46b86268c34fc5d0c3d9e76fd3665881a

轉bnb鏈接-https://bscscan.com/tx/0x2043939864abccf6ce7a90cf93059f8baac3f9248ae3c579d17ee93166183559

**Comment by 13392342238** [comment]
PLS CHECK

BSC-doge711-0x8c871119a51257BF92ad49EddECf2dB85054c3b6-https://bscscan.com/token/0x8c871119a51257bf92ad49eddecf2db85054c3b6

轉TPT鏈接-https://bscscan.com/tx/0xbf3d80c212c7eb0d2fbbe68db61a2110b5b0b8325e85758cad5d4f35209685bd
