### ISSUE TITLE
请查看#4668

### ISSUE THREAD

**Issue by Coinweth** [TP-Lab/tokens#4772]

**Comment by xwd1314191** [comment]
![logo](https://user-images.githubusercontent.com/87921921/148390305-d8583391-d162-4e82-bddc-a6d9f6945a2b.png)


> _没有提供说明。_

**Comment by xwd1314191** [comment]
[> _没有提供说明。_
](https://bscscan.com/tx/0x8e72059453d78fc2ddec28ead5fb03aaf64842c6cdb58223d3f7cf35409bb769)

**Comment by xwd1314191** [comment]
https://bscscan.com/tx/0x8e72059453d78fc2ddec28ead5fb03aaf64842c6cdb58223d3f7cf35409bb769

**Comment by xwd1314191** [comment]
![logo](https://user-images.githubusercontent.com/87921921/148391626-68aaffc0-e7bf-4a6e-ad05-0a204ecd032c.png)
![logo](https://user-images.githubusercontent.com/87921921/148391669-2577346a-7144-47c7-a446-e70e2d8f3565.png)

**Comment by giki0318** [comment]
Please submit your logo through PR
