### ISSUE TITLE
Add Logo / New Lisiting

### ISSUE THREAD

**Issue by NAAMToken** [TP-Lab/tokens#4849]
![0xc81ab0514c6ada6e3d55782219d7ca73345edf63](https://user-images.githubusercontent.com/94581534/148692263-05a67455-bf0a-428c-9298-80b4c0392695.png)

{
    "name": "Naanayam",
    "type": "BEP20",
    "symbol": "NAAM",
    "decimals": 18,
    "website": "https://naamtoken.com/",
    "description": "Naanayam (NAAM) is a cryptocurrency, deployed on Binance Smart Chain(BSC BEP-20)",
    "explorer": "https://bscscan.com/token/0xc81ab0514c6ada6e3d55782219d7ca73345edf63",
    "status": "active",
    "id": "0xc81ab0514c6ada6e3d55782219d7ca73345edf63"
}

**Comment by giki0318** [comment]
Please submit your logo through PR.
