### ISSUE TITLE
请审阅添加 PirateCat  徽标 和 信息 #4967

### ISSUE THREAD

**Issue by PirateCatcoin** [TP-Lab/tokens#4968]
BSC - TPT -0x6c5b69CfCDD4f6B31537B502259e6ECff0270f43 - https://bscscan.com/tx/0x0ef52781378e7aa27f04e766bccbb468afc9815372f507836c03e4c9d044a73e

**Comment by giki0318** [comment]
Please refer to the tutorial, and re-submit your files in the correct format.
