### ISSUE TITLE
Please Update FBU Logo, TPT 3000 Paid, thanks.

### ISSUE THREAD

**Issue by davidhe2015** [TP-Lab/tokens#5073]
https://github.com/TP-Lab/tokens/pull/5043
Token ID: 0xa7d101FC5C82C07E8F4FDbee34125C4b0906A675

IEO soon, Thanks a lot.

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by giki0318** [comment]
fixed
