### ISSUE TITLE
项目方代币地址0x4f58674f9eA4541A55fa96DFD3FFbF1e9e77c4de无法推送项目官网,logo信息

### ISSUE THREAD

**Issue by stvenyin** [TP-Lab/tokens#5160]
github账户:893692456@qq.com

**Comment by nenrgy** [comment]
专业提交logo,代币，白皮书，诚住经营，值得信赖，价格全网最优！QQ:2099728898
Professional submit logo, scrip, white paper, honestly live operation, reliable, the optimal price cut! QQ: 2099728898

**Comment by heipacker** [comment]
github的使用问题这个自己百度下吧
