### ISSUE TITLE
OA代币已经合并，但未生效，麻烦看一下

### ISSUE THREAD

**Issue by aibdgo** [TP-Lab/tokens#527]
合约地址：
0x5b6e3447408C65D5118BFb86C75a49313a77e125
合并记录：
https://github.com/TP-Lab/tokens/commit/a0da339384fd97d84d1fa168c38f0d9cca66831f#diff-5f75057e98eefa9da67b1a59d3d184f5c0315a905ebe0f6ddfe89aef6413c683
代币信息：
https://profile.tokenpocket.pro/#/token/107942208?locale=zh-CN&utm_source=tokenpocket
这个已经提交了代币logo，并且已经合并了，app内还是无法搜索看到logo，能麻烦你们看看吗？等了好几天了，摆脱

**Comment by littlemooose** [comment]
> 合约地址：
> 0x5b6e3447408C65D5118BFb86C75a49313a77e125
> 合并记录：
> [a0da339#diff-5f75057e98eefa9da67b1a59d3d184f5c0315a905ebe0f6ddfe89aef6413c683](https://github.com/TP-Lab/tokens/commit/a0da339384fd97d84d1fa168c38f0d9cca66831f#diff-5f75057e98eefa9da67b1a59d3d184f5c0315a905ebe0f6ddfe89aef6413c683)
> 代币信息：
> https://profile.tokenpocket.pro/#/token/107942208?locale=zh-CN&utm_source=tokenpocket
> 这个已经提交了代币logo，并且已经合并了，app内还是无法搜索看到logo，能麻烦你们看看吗？等了好几天了，摆脱

**Comment by littlemooose** [comment]
请在tpt上传标志小驼鹿

**Comment by zhujiayu03** [comment]
已经添加

**Comment by littlemooose** [comment]
You already added LittleMoose in Tokenpocket logo?

**Comment by littlemooose** [comment]
你在Tokenpocket中添加小驼鹿图标了吗？

**Comment by littlemooose** [comment]
你在Tokenpocket中添加小驼鹿图标了吗？
