### ISSUE TITLE
Why is the logo already displayed, but it disappears the next day after TP

### ISSUE THREAD

**Issue by scsp1064** [TP-Lab/tokens#5328]
It has been merged, The logo was displayed on the same day and disappeared the next day.

https://github.com/TP-Lab/tokens/tree/master/bsc/0x3C01EDA96A37A1C3dF760dE899139942Dc83695d

**Comment by scsp1064** [comment]
@sammvio  Can you help me see why the logo is not displayed ?

**Comment by giki0318** [comment]
merged
