### ISSUE TITLE
怎么上传代币头像

### ISSUE THREAD

**Issue by Wangni86** [TP-Lab/tokens#5384]
怎么上传代币头像

**Comment by MrMDC** [comment]
可以帮你做,有兴趣联络微信号jieweitexu123 或者 WhatsApp 01117460328

**Comment by heipacker** [comment]
看文档啊， 仓库里不是有说明吗

**Comment by MrMDC** [comment]
> 怎么上传代币头像

if you fail to upload the logo to TokenPocket , I can help you , find me , add my wechat- jieweitexu123 or QQ - 2486364041
