### ISSUE TITLE
The contract is not disclosed, and there may be some risks.

### ISSUE THREAD

**Issue by btcdao-vip** [TP-Lab/tokens#5762]
The contract is not disclosed, and there may be some risks.
Please re submit the logo after adjustment or optimization. Thank you for your support for tokenpocket.

_Originally posted by @opera0001 in https://github.com/TP-Lab/tokens/issues/5725#issuecomment-1047672764_、、是说合约没有开源吗？
是开源的啊  麻烦再查看下？

**Comment by giki0318** [comment]
Please re-submit your logo. It is not open-source while we were reviewing.
