### ISSUE TITLE
Git上显示已合并，但是app上看不到logo信息

### ISSUE THREAD

**Issue by zb305107** [TP-Lab/tokens#5911]
https://github.com/TP-Lab/tokens/pull/5323
TFIL 0x9FCbD498791C6A4DD01FA0d12526c357E680064a
merged 14 days ago

https://github.com/TP-Lab/tokens/pull/5514
BBM 0x17a85d5c277C77522bE09e14E147c55b06d559F9
merged 10 days ago

![Screenshot_2022-02-28-09-24-35-359_vip mytokenpocket](https://user-images.githubusercontent.com/28724083/155910353-790e9944-dbfb-485e-b95d-1d8722f03aae.jpg)
![Screenshot_2022-02-28-09-24-40-639_vip mytokenpocket](https://user-images.githubusercontent.com/28724083/155910363-c04f5666-db3b-4183-945e-0ce9833bcc9e.jpg)

**Comment by DaTang1233** [comment]
我刚才看你这个显示了
