### ISSUE TITLE
为And添加logo以及代币信息

### ISSUE THREAD

**Issue by 45567867** [TP-Lab/tokens#594]
代币名称 ：  And
总供应量：10000000000000000
小数位数：18
合约地址：0xf5c16e01ad2ad6c223ab719401c65c3e84133645
官网信息：http://qmah.53mayi.com/index.html
项目简介：为黑暗而生。
![andlogo](https://user-images.githubusercontent.com/86392558/123196452-88538280-d4dc-11eb-8a80-e9f6287153c1.png)

**Comment by zhujiayu03** [comment]
请提交至PR
