### ISSUE TITLE
为And添加logo和代币信息

### ISSUE THREAD

**Issue by 45567867** [TP-Lab/tokens#595]
代币名称 ： And
总供应量：10000000000000000
小数位数：18
合约地址：0xf5c16e01ad2ad6c223ab719401c65c3e84133645
官网信息：http://qmah.53mayi.com/index.html
项目简介：为黑暗而生。
![andlogo](https://user-images.githubusercontent.com/86392558/123196522-aa4d0500-d4dc-11eb-8b77-3c4b5d8b6c80.png)

**Comment by zhujiayu03** [comment]
请提交至PR

**Comment by 45567867** [comment]
Ok ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月28日(星期一) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TP-Lab/tokens] 为And添加logo和代币信息 (#595)

**Comment by 45567867** [comment]
> 请提交至公关

怎么提交
