### ISSUE TITLE
Now you need 30000 TPT donation fees to submit the token logo collection. Please supplement and send the hash value to the message of GitHub.

### ISSUE THREAD

**Issue by woodmaxkid** [TP-Lab/tokens#6072]
Now you need 30000 TPT donation fees to submit the token logo collection. Please supplement and send the hash value to the message of GitHub.

_Originally posted by @opera0001 in https://github.com/TP-Lab/tokens/issues/6003#issuecomment-1059702458_

Do I submit in the original project or create a new one and submit again

**Comment by pmmt** [comment]
0x0eabed5419c972c1de80895170b7ce5d1a067c041ce37cab0b1ac9ef07e7c6b5

**Comment by chenyige2018** [comment]
BSC-OSNC-0x191608adaEd4c10930FE8749c5221B23619bE0C0-https://bscscan.com/tx/0xd7b0ed14c0aee8490bd7e5a777541191d615b40dd2ed9fa2a81b6b61d3c9b8fa

请帮审核通过呀

**Comment by opera0001** [comment]
![image](https://user-images.githubusercontent.com/99245006/158014185-965255a7-0d21-40ee-84ca-19b10054dfc6.png)
It's not the same thing, is it?

**Comment by EXPERTDOGE** [comment]
0xafeb208b41fbca32035b00d1e6318f1078d0a712e46eecb101db8073164bf32f
