### ISSUE TITLE
0xfd15fa4ef538e6253A9EDd4CC2f56D9bbc0faD23

### ISSUE THREAD

**Issue by CrayonLivermore** [TP-Lab/tokens#625]
token合约：0xfd15fa4ef538e6253A9EDd4CC2f56D9bbc0faD23
官网：https://www.creatorchain.network/
简称：CRT
logo提交
<img width="100" alt="CTR" src="https://user-images.githubusercontent.com/84384494/123236139-1cd6d880-d50f-11eb-9411-de7549132eec.png">

**Comment by zhujiayu03** [comment]
请提交至Pull requests
