### ISSUE TITLE
Add OPM and info #560  图标未更新

### ISSUE THREAD

**Issue by OptimumFinance** [TP-Lab/tokens#641]
ID:418bfe7c53ac042bda047d11af546d7df96a3d22
已审核通过 图标未更新
代币：0x03FDD2EDf418A870A070D3baB0C6d1Ad4DBC70B4

**Comment by zhujiayu03** [comment]
请提供您的Pull request链接以便查看。

**Comment by OptimumFinance** [comment]
https://github.com/OptimumFinance/tokens/commit/418bfe7c53ac042bda047d11af546d7df96a3d22

**Comment by OptimumFinance** [comment]
https://github.com/OptimumFinance/tokens/commit/418bfe7c53ac042bda047d11af546d7df96a3d22
________________________________
发件人: zhujiayu03 ***@***.***>
发送时间: 2021年6月30日 10:04
收件人: TP-Lab/tokens ***@***.***>
抄送: OptimumFinance ***@***.***>; Author ***@***.***>
主题: Re: [TP-Lab/tokens] Add OPM and info #560 图标未更新 (#641)


请提供您的Pull request链接以便查看。

―
