### ISSUE TITLE
Modify whether the NFT icon of erc721 type can be submitted in this warehouse

### ISSUE THREAD

**Issue by MingHuiLiu** [TP-Lab/tokens#6450]
Whether the NFT icon of erc721 type can be modified by pressing https://tphelp.gitbook.io/cn/wallet-operation/submit-token This method is submitted in this warehouse

**Comment by opera0001** [comment]
Yes, no problem. You only need to make a brief explanation after submission, for example, it is erc-721 token.

**Comment by MingHuiLiu** [comment]
Thank you very much for your reply,
 and I would like to ask you for advice when the contract is of the nft type. 
1. Whether the "symbol" and "decimals" in the description file take effect when the UI is rendered. 
2. If the effective nft name is displayed as "name" or "symbol"?
3. Do you need to fill in 0 if you want to keep the decimals displayed as they are?
[IMAGE](http://r9inbcwy0.hn-bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20220330174019.jpg)
 Looking forward to hearing from you again, thank you very much

**Comment by opera0001** [comment]
Fill in according to the content required in JSON, such as precision, token name and so on.
