### ISSUE TITLE
Attached BIB Logo for TokenPocket Application

### ISSUE THREAD

**Issue by mikeseah99** [TP-Lab/tokens#6463]
Attached BIB Logo for TokenPocket Application - pls refer to the attachment logo fil
[BIB logo.pdf](https://github.com/TP-Lab/tokens/files/8370113/BIB.logo.pdf)
[BIB logo.psd.zip](https://github.com/TP-Lab/tokens/files/8370118/BIB.logo.psd.zip)
e

**Comment by giki0318** [comment]
How to submit
https://tphelp.gitbook.io/en/wallet-operation/how-to-submit-a-token-logo
