### ISSUE TITLE
Apply to update logo

### ISSUE THREAD

**Issue by jxu9318** [TP-Lab/tokens#6787]
Apply for the logo file of the update #6721 order, and the hash value link submitted is
https://bscscan.com/tx/0x62e048da9ea1cb43dc68a5cf12f98d7fd3dfbc74afd09483a0146f13f0553bf4
https://bscscan.com/tx/0x2675ee6592ad1d8f60cab6940a9d9d830973e3e3b401024229ab4d5a2c9bbaf1

![logo](https://user-images.githubusercontent.com/103606099/163722728-806bde96-3ecb-459b-9de8-da1bbb9ed11a.png)

This is the newly submitted logo file, thank you.

**Comment by opera0001** [comment]
Done
