### ISSUE TITLE
添加代币logo

### ISSUE THREAD

**Issue by yiyi1025-SRIT** [TP-Lab/tokens#695]
代币名称 ： HMS
总供应量：10000000000
小数位数：10
合约地址：0x3900eD7317208b9fD1B6fB792F5C8cC74Bb05E8D
官网信息：https://harmony-paris.com/
项目简介：最强黑洞
![image](https://user-images.githubusercontent.com/72469414/123513267-cf00d280-d6be-11eb-87eb-072cce146565.jpeg)

**Comment by zhujiayu03** [comment]
请提交至Pull requests
