### ISSUE TITLE
NFT is OK!

### ISSUE THREAD

**Issue by STARGlobal** [TP-Lab/tokens#7033]

**Comment by STARGlobal** [comment]
![image](https://user-images.githubusercontent.com/103128034/167132231-740a1d73-5b64-417f-ab4d-672f44e162af.png)
Please help!

NFT with a brief introduction
![image](https://user-images.githubusercontent.com/103128034/167132275-4ae28c89-46ed-433e-a6d1-e8ab3f8e8fe7.png)

**Comment by opera0001** [comment]
I don't understand what you want to express. Please explain your complete question. If there is a number, please provide the number submitted under. Thank you.
