### ISSUE TITLE
After FLS(0x0b165ed2633e08fe5e778e085e95c1c9b52e300d) updated the logo, there is no logo, please check it urgently!!!

### ISSUE THREAD

**Issue by flames66** [TP-Lab/tokens#7126]
![image](https://user-images.githubusercontent.com/101155597/168456235-51713dba-a189-404e-89ca-5235306ebae0.png)

**Comment by flames66** [comment]
![image](https://user-images.githubusercontent.com/101155597/168458466-ed775151-ba6c-46a7-b472-bb0f22f34b04.png)
The official website has been released

**Comment by opera0001** [comment]
It has been restored that the sale must leave 0.0001 tokens, which people should encounter some problems that they can't sell all.
