### ISSUE TITLE
We had some issues

### ISSUE THREAD

**Issue by Hansenkatrine** [TP-Lab/tokens#7167]
Dear TokenPocket Good morning!
We had some issues, our token Nobelcoin (NBC) wanted to update the token logo, but after submitting it was rejected and the response we got was: "Nobel is a famous person, and we don't think that a Noblecoin is suitable to be issued by meme community." We have now made rectifications and affirmed that the NBC token is not issued by a certain community, I hope the TokenPocket reviewers will review it again, and I wish you a wonderful day!

**Comment by opera0001** [comment]
Suggestions have been given to you in the order, please check.
