### ISSUE TITLE
添加LOGO后 显示“已验视”但钱包还是不显示

### ISSUE THREAD

**Issue by ht2012hb** [TP-Lab/tokens#724]
添加LOGO后 显示“已验视”但钱包还是不显示，是按照TP官网公布的教程添加的，谁知道是哪里错误了吗

**Comment by zhujiayu03** [comment]
请提交代币名称和合约以便查看。

**Comment by ht2012hb** [comment]
合约地址：
0x4a6E12F904025002741bfBbFd3146C0E8C0329e0

代币名称：BPB
请帮忙查看下是不是我提交格式有错误谢谢官方指导，非常感谢

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月27日(周日) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TP-Lab/tokens] 添加LOGO后 显示“已验视”但钱包还是不显示 (#724)




 
请提交代币名称和合约以便查看。

**Comment by ht2012hb** [comment]
代币名称：BPB
合约：
0x4a6E12F904025002741bfBbFd3146C0E8C0329e0


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月27日(周日) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TP-Lab/tokens] 添加LOGO后 显示“已验视”但钱包还是不显示 (#724)




 
请提交代币名称和合约以便查看。
