### ISSUE TITLE
请问如何为同一个合约中，两种属性的NFT，提交相对应的图片，谢谢

### ISSUE THREAD

**Issue by hetaoxiao** [TP-Lab/tokens#7255]
请问如何为同一个合约中，两种属性的NFT，提交相对应的图片。我只在官网看见了提交NFT的资料和LOGO的接口文档。需要在TP钱包中NFT页面添加NFT的合约之后，点进添加后的合约，能在自己持有的NFT发送页面查看到最上方占了屏幕三分之一大小的NFT图片。想请问上述图片是如何添加的？
或者直接在opensea上架了该NFT的详细信息和每个NFT对应的图片之后，可以在TP钱包的NFT发送页面看见该NFT的图片吗？
![微信图片_20220526214931](https://user-images.githubusercontent.com/94629506/170500948-5f647f77-91d0-41fe-84fd-80442b7729e4.png)

**Comment by opera0001** [comment]
What is submitted in the submission portal of the official website is the logo corresponding to your NFT contract address, not the internal specific binding picture, so they are not a concept. I'm sorry I can't answer the specific technical questions for you.

**Comment by hetaoxiao** [comment]
> 官网提交门户中提交的是你的NFT合约地址对应的logo，而不是内部具体的绑定图片，所以它们不是一个概念。很抱歉，我无法为您回答具体的技术问题。

谢谢，请问TP钱包可以读取上架opensea上的NFT图片吗，我发送的截图就是没有在TP官网提交项目信息，但是仍然能看到NFT的图片。

**Comment by hetaoxiao** [comment]
或者说TP钱包支持读取哪些NFT交易平台的链上NFT的json文件呢

**Comment by opera0001** [comment]
> 或者说TP钱包支持读取哪些NFT交易平台的链上NFT的json文件呢

As long as your NFT is open source and the JSON you use is daily, you can read the pictures inside.

**Comment by opera0001** [comment]
> 

The pictures on opensea are the same, and we can read them.

**Comment by opera0001** [comment]
The pictures on opensea are the same, and we can read them.

**Comment by hetaoxiao** [comment]
> 

我现在用的通过tokenURI读取json地址，json文件也是用的标准格式，和我一样的其他的NFT可以在TP钱包读取到名字和图片，为什么我的NFT在TP钱包读取不到呢
