### ISSUE TITLE
Logo not clear issue

### ISSUE THREAD

**Issue by RMCMO999** [TP-Lab/tokens#7268]
Hi I have submitted a logo which is not very clear, will the logo still shown in token pocket? If yes, there's no need to change it again, if not, where can I submit the new logo?

<img width="919" alt="Screen Shot 2022-05-27 at 6 13 55 pm" src="https://user-images.githubusercontent.com/105790861/170659580-c188446f-4acf-4fbf-a81e-a720506d5f29.png">

**Comment by opera0001** [comment]
This has been successfully included. The tips here are just personal suggestions. If you don't think it needs to be modified, you don't have to worry about this problem. Now the logo is displayed normally. Please rest assured.
