### ISSUE TITLE
The settings that can control the circulation of tokens are detected, which is very risky.

### ISSUE THREAD

**Issue by AvatarMetaverse** [TP-Lab/tokens#7494]
https://github.com/TP-Lab/tokens/pull/7391
We have made a switch that we will not buy a few days before the launch. How can we pass the review if the contract cannot be modified after the launch

**Comment by AvatarMetaverse** [comment]
Can the discard permission pass the audit after the buy switch is turned on in a few days

**Comment by opera0001** [comment]
It is still recommended that you re apply with us after the token transaction starts, because it is risky to leave the function that can control the transaction. so sorry.

**Comment by AvatarMetaverse** [comment]
Can the original TPT payment be used to reapply after token purchase is enabled? This contract with a buy switch can pass as long as the transaction application is enabled

**Comment by opera0001** [comment]
After normal token transactions, if you can give up the administrator permission and resubmit, you do not need a new TPT hash value.

**Comment by AvatarMetaverse** [comment]
Well, thank you
