### ISSUE TITLE
Readjust SPACE COIN logo #7508

### ISSUE THREAD

**Issue by JasoniMatthewsF42l** [TP-Lab/tokens#7548]
Hello @opera0001 I wish to readjust the size and the logo for SPACETOKEN from pull request #7508
![logo png](https://user-images.githubusercontent.com/107618213/174483902-0369947c-ade8-4a52-bff2-d32b7e5f8bb4.png)

**Comment by JasoniMatthewsF42l** [comment]
@opera0001

**Comment by opera0001** [comment]
done
