### ISSUE TITLE
Modify MXT token logo and price

### ISSUE THREAD

**Issue by Mixtrust** [TP-Lab/tokens#7594]
1. Token logo: https://drive.google.com/file/d/12ztANmV1lmClNbfMYyWm0I1LglP7_3eu/view?usp=sharing
2. MXT price: https://www.okx.com/trade-spot/mxt-usdt
3. MXT website: https://mixtrust.exchange/

**Comment by opera0001** [comment]
Sorry, I didn't understand what you meant.

**Comment by Mixtrust** [comment]
Hey, TP team,

Thank you for your feedback. We just submitted another request, pls see
this link:
https://github.com/TP-Lab/tokens/pull/7604
for changing the logo according to your request with 50000 TPT sent. Cause
MXT token’s logo is wrong in TP wallet, and can’t show MXT price. Pls refer
to coinmarketcap or uniswap token price to fix it. Pls help to check this
request.

Thank you!

opera0001 ***@***.***> wrote on June 25th 22:09
