### ISSUE TITLE
补充TPT捐赠数量

### ISSUE THREAD

**Issue by llawdao** [TP-Lab/tokens#7608]
当我根据文档提交图标时，文档上显示的捐赠数量是30000个，现在再来看已经变成了50000个，我应该怎样补上剩下的20000个TPT，才能保证图标审核通过 #7585

**Comment by opera0001** [comment]
Very simply, you only need to transfer to the specified address 20000tpt again, and then the TPT hash value is normally submitted to the order.

**Comment by llawdao** [comment]
> Very simply, you only need to transfer to the specified address 20000tpt again, and then the TPT hash value is normally submitted to the order.

20000TPT-> https://bscscan.com/tx/0x6d82566942f7396f88e31053a047e81f482194f982dc8a8e93a447dfbbcf7129?utm_source=tokenpocket

**Comment by opera0001** [comment]
done
