### ISSUE TITLE
logo submission error 

### ISSUE THREAD

**Issue by EGNtoken** [TP-Lab/tokens#7657]
admin, we submitted the contract address of the test token, our official version of the contract address should be 0x312104384dD59fab22506fE6A61736EE75d94C9E , how do I fix it
https://github.com/TP-Lab/tokens/pull/7633

**Comment by opera0001** [comment]
Have helped you to replace, the next submission do not submit in the message, you need to provide the normal contract address in the json.

**Comment by EGNtoken** [comment]
thanks.It's so kind of you

**Comment by EGNtoken** [comment]
> Have helped you to replace, the next submission do not submit in the message, you need to provide the normal contract address in the json.

When will the app be updated?
