### ISSUE TITLE
How to get off the old contract logo 

### ISSUE THREAD

**Issue by nftswapbscn** [TP-Lab/tokens#7756]
Hi

Update a new Token contract, how do you get off the old contract logo,The new contract has re -applied for logo

Old Contract address: 0x602940F3e043Fef5647783a8cF1639028620166b 

Tks!

**Comment by opera0001** [comment]
All you need to do is resubmit the order using the github account that provided the logo for this old contract and state that you need to remove the logo from the old contract address.
