### ISSUE TITLE
已合并TP钱包未显示图标

### ISSUE THREAD

**Issue by bitcoinaim** [TP-Lab/tokens#776]
名称BCA，合约地址：TFwmrUs7fb3hGn9jvDWDpNdJy3sbigS1uu 链：波场tron

**Comment by zhujiayu03** [comment]
请提供Pull request链接以便查看。

**Comment by bitcoinaim** [comment]
> 请提供Pull request链接以便查看。

https://github.com/TP-Lab/tokens/pull/538
