### ISSUE TITLE
A possible token increase issuance feature is detected, please check.

### ISSUE THREAD

**Issue by keen-finance** [TP-Lab/tokens#7795]
A possible token increase issuance feature is detected, please check.

_Originally posted by @opera0001 in https://github.com/TP-Lab/tokens/issues/7780#issuecomment-1186834289_

Due to business requirements, additional tokens must be issued, but the contract has hard-coded a limit of 10 million additional tokens. What should I do to meet the demand for additional tokens?

**Comment by opera0001** [comment]
OK, I understand. Please be patient and wait for the adoption.
