### ISSUE TITLE
Explain for the increase issue and decrease issue of token AFA (see more in pull request #7767)

### ISSUE THREAD

**Issue by ppaddan330** [TP-Lab/tokens#7824]
Dear TP-Lab, We're sorry for the pull request #7767 closed. Here's the detailed description about why the token AFA increase or decrease:

AFA's Token Supply Mechanism
AFA is a decentralised reserve asset token. Each AFA issue is backed by an intrinsic value in the treasury protocol. This intrinsic value is always greater than or equal to 1 USDT.

Therefore, as the treasury continues to receive USDT through the bonding mechanism, the protocol continues to mint new AFAs, a portion of which is distributed to bonding users at the bond price. The portion of the profit which above 1 USDT, new AFA will be minted and distributed to all stakers.

When the market price falls below 1USDT, the protocol can be reversed to recover the AFA, burn it off and releasing the USDT.

So the mechanism for issuing AFAs is a circular supply model, and in theory there is no upper limit to the issuance of AFAs as long as the treasury keeps acquiring assets. And the lower limit for AFAs is zero.

Please review our request again. Thank you very mush !

**Comment by opera0001** [comment]
Completed
