### ISSUE TITLE
Squidgrow logo update request canceled

### ISSUE THREAD

**Issue by squidgrowtoken** [TP-Lab/tokens#7862]
Sorry for delayed response, The person responsible for the github was on leave of few days so missed the update and further information request.
This is regarding the pull request https://github.com/TP-Lab/tokens/pull/7820 . 
Can you please elaborate on what function you see issue with? We are listed on Bitmart and Bkex, They found contract to be fine. Please find the audit report here.
https://solidity.finance/audits/SquidGrow/

Please let us know the issue and we will try to solve it asap.
Thank you.

**Comment by opera0001** [comment]
Processing completed
