### ISSUE TITLE
IRON

### ISSUE THREAD

**Issue by sunny-veto** [TP-Lab/tokens#7897]
A new info file has been submitted；For the safety of the funds of the lp pool, we have set the possibility to suspend the transaction；Can not sell 100%, need to reserve 0.01 tokens, we have full-time preachers to explain the situation to the holders；Adjustable transaction rates allow us to better control token prices；We don't know about other issues with tokens

**Comment by opera0001** [comment]
Please let me know this github order number for your feedback question, thanks.

**Comment by sunny-veto** [comment]
order has been closed;;0xe30Fa338f2a620fA7824D567046B4a9ef6A3c6e9/info.json
{
 "name": "SUPERN HERO TOKENS",
 "website": "https://www.superironman.org",
 "description": "Super Hero aims to combine the physical industry with the digital economy, shape the new superhero Yuan universe space, break the "island effect" between different fields, integrate it into a whole The drainage mechanism prompts more users to participate in the experience of our superhero.",
 "explorer": "https://bscscan.com/token/0xe30fa338f2a620fa7824d567046b4a9ef6a3c6e9",
 "type": "BEP20",
 "symbol": "IRON",
 "decimals": 18,
 "status": "active",
 "id": "0xe30fa338f2a620fa7824d567046b4a9ef6a3c6e9"
}
