### ISSUE TITLE
Ownership statement of the contract

### ISSUE THREAD

**Issue by metaverse-dao** [TP-Lab/tokens#7944]
Sorry, we are submitting the token LOGO of TP for the first time
So didn't notice the reply before, so it took more than 3 days to find out
Last Issue https://github.com/TP-Lab/tokens/pull/7871

Token: Metaverse-DAO (METADAO)
Contract: 0x6195D22d416E2D2c7C4A883c977Dd9Bfd4e65432

About the ownership of the contract:
The owner can give up the ownership of the contract, the contract has passed the audit and obtained the certificate. the audit company had confirmed the logic of ownership is no problem. If the owner gives up the ownership, then will not be able to get it back again, and we have not given up the ownership of the contract yet.
Audit link: https://github.com/solidproof/projects/tree/main/Metaverse-DAO
The contract can also be locked, and the owner cannot unlock it during the locking period. Only after the locking period can the ownership be obtained again, and once the ownership is given up, it cannot be retrieved again.

**Comment by opera0001** [comment]
Settings found that can retrieve control, please check.

**Comment by metaverse-dao** [comment]
Hello

The contract currently has 2 ways to renounce control
A
locks the contract, my reply is yes, the owner can retrieve control the contract after the lock-up period if the contract is locked
B
Renounce ownership of the contract, founder will lose control and there is no way to retrieve control if Renounce ownership

I don't know if this is detailed enough
If the reply is not for the question you asked, please tell me which line of code you are referring to? Many thanks

Best Regards,
Metaverse - DAO Team

**Comment by metaverse-dao** [comment]
Hi opera0001 
Do you need us to answer any questions?
We are anxiously awaiting your feedback

**Comment by opera0001** [comment]
Already processed

**Comment by metaverse-dao** [comment]
Thanks for your feedback and have a great day
