### ISSUE TITLE
issue about not replying to translation rate

### ISSUE THREAD

**Issue by Floki-Doge** [TP-Lab/tokens#7977]
We will use translation rate to anti bot for protect our holders' benefit. 
We will give up the ownership after launch.
We need the ownership for presale whitelist,so we can't drop it now.

**Comment by opera0001** [comment]
Please tell us what is the order number for this issue you are feeding back?
Thank you

**Comment by Floki-Doge** [comment]
We will use translation rate to anti bot for protect our holders' benefit.
We will give up the ownership after launch.
We need the ownership for presale whitelist,so we can't drop it now.

**Comment by opera0001** [comment]
Please tell us what is the order number for this issue you are feeding back?
Thank you

**Comment by Floki-Doge** [comment]
7983

**Comment by opera0001** [comment]
Completed
