### ISSUE TITLE
Add eat logo and info

### ISSUE THREAD

**Issue by eataddproton** [TP-Lab/tokens#7996]
BSC-eat-0xbC2Cf7500a4c44E5e67020069418584971F5Ce0D- [https: //bscscan.com/tx/0xc1be1b7684ef21bbbfe2e9ad133cd3cdd984f4bae3132fe40f52e93bba64ed45](https://bscscan.com/tx/0xc1be1b7684ef21bbbfe2e9ad133cd3cdd984f4bae3132fe40f52e93bba64ed45)

**Comment by opera0001** [comment]
Can you tell me which github order number this is a hash value to add?

**Comment by eataddproton** [comment]
github order number  #7937 

BSC-EAT-0xbC2Cf7500a4c44E5e67020069418584971F5Ce0D- [https: //bscscan.com/tx/0xc1be1b7684ef21bbbfe2e9ad133cd3cdd984f4bae3132fe40f52e93bba64ed45](https://bscscan.com/tx/0xc1be1b7684ef21bbbfe2e9ad133cd3cdd984f4bae3132fe40f52e93bba64ed45)

**Comment by eataddproton** [comment]
github order number #7937
BSC-EAT-0xbC2Cf7500a4c44E5e67020069418584971F5Ce0D- [https: //bscscan.com/tx/0xc1be1b7684ef21bbbfe2e9ad133cd3cdd984f4bae3132fe40f52e93bba64ed45](https://bscscan.com/tx/0xc1be1b7684ef21bbbfe2e9ad133cd3cdd984f4bae3132fe40f52e93bba64ed45)

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
