### ISSUE TITLE
We have upgraded the contract

### ISSUE THREAD

**Issue by LiteUSD** [TP-Lab/tokens#8097]
Old LITE contract: 0x4a846d300f793752ee8bd579192c477130c4b369
New LITE contract: 0x3ef3f6cf9f867a33c4109208a6bd043a9ef0e091

Please replace the old contract.

**Comment by opera0001** [comment]
Please provide the order number of github.

**Comment by LiteUSD** [comment]
#7568

**Comment by LiteUSD** [comment]
BSC

**Comment by LiteUSD** [comment]
BEP20

**Comment by opera0001** [comment]
Sorry, your historical order was submitted a long time ago, so if you need to change to a new contract address, you need to submit your order again via github and fill in the description information.

**Comment by LiteUSD** [comment]
Pull request again? Need to donate TPT again?

**Comment by opera0001** [comment]
Yes, because it is necessary to change the contract address and not the logo.
