### ISSUE TITLE
We upgraded our contract

### ISSUE THREAD

**Issue by 3150769565** [TP-Lab/tokens#8127]
0xF325ca741aAf478859aa2e9b1AF37a21f24aE960
https://github.com/3150769565/tokens/commit/8e09c231c5c36140a2465ad3516bb92a48b6b9e8
The image has been changed to 256 pixels

**Comment by 3150769565** [comment]
![logo png](https://user-images.githubusercontent.com/110765315/187357700-5f635d4a-b767-4e58-b833-2bf4bcdb79bb.png)

**Comment by opera0001** [comment]
Which github order-related information did you submit?

**Comment by 3150769565** [comment]
https://github.com/3150769565/tokens/commit/8e09c231c5c36140a2465ad3516bb92a48b6b9e8

**Comment by 3150769565** [comment]
添加狼标志和信息
[https://bscscan.com/tx/0xea2453cfa02ff219e4fdf02098ccb1ba36e721ce3998bab6c93097fe695ddf11 ](https://bscscan.com/tx/0xea2453cfa02ff219e4fdf02098ccb1ba36e721ce3998bab6c93097fe695ddf11)
[https://bscscan.com/tx/0x5a337ebb3fbde0ec472a7fb45e04600a841a04e82847f98729d30e](https://bscscan.com/tx/0x5a337ebb3fbde0ec472a7fb45e04600a841a04e8247f98729e00895d2f5c1723)

**Comment by opera0001** [comment]
It is detected that the token contract code is not disclosed, so it is impossible to detect whether it is safe. If it is inconvenient to disclose, the audit report of the security audit department can be submitted.

**Comment by 3150769565** [comment]
已经公开 了啊、

**Comment by opera0001** [comment]
![image](https://user-images.githubusercontent.com/99245006/187702433-cf8b7c48-792e-476d-9337-dcf799849742.png)
https://bscscan.com/token/0xF325ca741aAf478859aa2e9b1AF37a21f24aE960#readContract
