### ISSUE TITLE
修改代币logo

### ISSUE THREAD

**Issue by zhihuiin** [TP-Lab/tokens#8166]
你好，我们于9.2号收录了代币logo，如今我们项目修改了logo，麻烦帮忙修改一下，这里是merge记录https://github.com/TP-Lab/tokens/pull/8125

![a5a5951f099322fa6bd8f1a789ad9bf](https://user-images.githubusercontent.com/112459335/188254201-110e7d21-c906-461c-858f-8407cf1ad2f2.jpg)

**Comment by opera0001** [comment]
Done
