### ISSUE TITLE
It was detected that the tokens could not all be sold.

### ISSUE THREAD

**Issue by Kelvinorin** [TP-Lab/tokens#8197]
This is a part of token design to keep the holder members up.
Holders can sell all tokens when they set the sell amount as 10000/10045 of balance.

It was detected that the tokens could not all be sold.

_Originally posted by @opera0001 in https://github.com/TP-Lab/tokens/issues/8184#issuecomment-1237906650_

**Comment by jtkno11** [comment]
卖出是每次99%

**Comment by 1151876150** [comment]
This is a part of token design to keep the holder members up.
Holders can sell all tokens when they set the sell amount as 10000/10045 of balance.
