### ISSUE TITLE
添加狼标志和信息

### ISSUE THREAD

**Issue by 3150769565** [TP-Lab/tokens#8238]
https://github.com/3150769565/tokens/commit/8e09c231c5c36140a2465ad3516bb92a48b6b9e8

**Comment by 3150769565** [comment]
添加狼标志和信息
[https://bscscan.com/tx/0xea2453cfa02ff219e4fdf02098ccb1ba36e721ce3998bab6c93097fe695ddf11 ](https://bscscan.com/tx/0xea2453cfa02ff219e4fdf02098ccb1ba36e721ce3998bab6c93097fe695ddf11)
[https://bscscan.com/tx/0x5a337ebb3fbde0ec472a7fb45e04600a841a04e82847f98729d30e](https://bscscan.com/tx/0x5a337ebb3fbde0ec472a7fb45e04600a841a04e8247f98729e00895d2f5c1723)

**Comment by 3150769565** [comment]
代码已经开源

**Comment by 3150769565** [comment]
![logo png](https://user-images.githubusercontent.com/110765315/190856485-423187bd-5530-4ad2-9869-65e87fe7c3e5.png)

**Comment by opera0001** [comment]
done
