### ISSUE TITLE
Logo timeout request

### ISSUE THREAD

**Issue by elelogo** [TP-Lab/tokens#8316]
Hello: 
        My logo application has timed out. What should I do?
        https://github.com/TP-Lab/tokens/pull/8267

**Comment by opera0001** [comment]
You need to check what the hidden owner permissions are.

**Comment by elclogo** [comment]
In the parent class of black-and-white list, there is an owner permission to control the setting of black-and-white list

**Comment by elclogo** [comment]
I have no intention to hide owner permissions, but that's just the structure of the code.

**Comment by elclogo** [comment]
![logo](https://user-images.githubusercontent.com/114016866/192891040-325af22c-56d8-4fb0-9e76-9c70b6a94023.png)

**Comment by elelogo** [comment]
Sorry, I didn't pay attention to the comment account just now. ELE and ELC are a pair of Tokens. The comments of the elclogo user above are valid

**Comment by opera0001** [comment]
Is it possible to take a screenshot of the code that hides the owner section and explain it.

**Comment by elclogo** [comment]
![telegram-cloud-photo-size-5-6179417496457688915-y](https://user-images.githubusercontent.com/114016866/193414763-f57b169a-bd6f-4143-abb5-bfcd7c2f0595.jpg)
![telegram-cloud-photo-size-5-6179417496457688916-y](https://user-images.githubusercontent.com/114016866/193414777-05521174-ada0-4aa6-8e68-d691878d8819.jpg)
![telegram-cloud-photo-size-5-6179417496457688917-y](https://user-images.githubusercontent.com/114016866/193414786-71ad9670-7049-415b-b3ee-83170e6c4aed.jpg)
Contract EleToken does not need to use permission control, so It’s not inherit the AccessControl

**Comment by elclogo** [comment]
![telegram-cloud-photo-size-5-6179417496457688919-y](https://user-images.githubusercontent.com/114016866/193415005-c2373c40-e56b-4fa1-843f-f784e924217d.jpg)

**Comment by elclogo** [comment]
![telegram-cloud-photo-size-5-6179417496457688922-y](https://user-images.githubusercontent.com/114016866/193415554-e4f81a1e-d48b-4a61-bcfd-219e42940e03.jpg)

**Comment by opera0001** [comment]
done
