### ISSUE TITLE
Timeout in submitting logo

### ISSUE THREAD

**Issue by elclogo** [TP-Lab/tokens#8317]
Hello: 
I'm sorry that I failed to deal with the problem you raised in time. How can I deal with it later?
https://github.com/TP-Lab/tokens/pull/8265

**Comment by opera0001** [comment]
Your question is very simple, just adjust the pixel of the logo and explain why you can change the token rate, the logo can be sent to me via issues.

**Comment by elclogo** [comment]
![logo](https://user-images.githubusercontent.com/114016866/192891269-2a190473-1ee8-44b9-b50a-7b1e3d1bbf00.png)

**Comment by elclogo** [comment]
ELE and ELC are a pair of token, and their price is related. ELE will buy back ELC when trading. This buy back ratio is variable and used to control their exchange rate
