### ISSUE TITLE
Change logo as the previous one not fit #8279

### ISSUE THREAD

**Issue by BIBToken** [TP-Lab/tokens#8323]
@opera0001 would like to request can we change the logo as the previous one doesn't seem fit. Sorry for that. https://github.com/TP-Lab/tokens/pull/8279
![logo png](https://user-images.githubusercontent.com/114157321/192939661-41bcfb81-db3f-4c84-9fe9-5b7af07b2830.png)

**Comment by opera0001** [comment]
done
