### ISSUE TITLE
Add logo to my projekt token

### ISSUE THREAD

**Issue by openartstudio** [TP-Lab/tokens#8341]
Hello
How can I add logo to my projekt token on polygon?
I have file: 
0x6daA1e9CDFe153974761709a091d5665eABC3619.png
Regards
Jacek Kolodziejczak

**Comment by opera0001** [comment]
https://tphelp.gitbook.io/en/wallet-operation/how-to-submit-a-token-logo
Just follow this tutorial to submit a logo.

**Comment by openartstudio** [comment]
> https://tphelp.gitbook.io/en/wallet-operation/how-to-submit-a-token-logo Just follow this tutorial to submit a logo.

ok thank you
