### ISSUE TITLE
显示“已验视”但是TP钱包还是不显示LOGO

### ISSUE THREAD

**Issue by ht2012hb** [TP-Lab/tokens#835]
显示“已验视”但是TP钱包还是不显示LOGO 请帮忙看看是不是提交的资料有误还是什么呢？？？谢谢

代币名称：BPB

合约地址：0x4a6E12F904025002741bfBbFd3146C0E8C0329e0

合并链接：https://github.com/TP-Lab/tokens/commit/7492251cb64f65ee8934aee24e1349e0660c3986#diff-681395c2573bc5d79b255b4ebe3696be73d84dc2016057656e9babb3caac0e7b

**Comment by zhujiayu03** [comment]
请再次刷新查看。
