### ISSUE TITLE
add BOXC token logo

### ISSUE THREAD

**Issue by ubunt2022** [TP-Lab/tokens#8353]
https://bscscan.com/tx/0x3a6d021b6cf3038cf5630af8195b590388b1f1544546f69b535d0bd6043c7fe4 捐赠 https://bscscan.com/tx/0xecb7c9d0c400d4bce459f55e55f43ff49b75d6649adb087cf983cbfddedab12c 验证

new logo is
![logo](https://user-images.githubusercontent.com/100547467/194460596-eb4fddfc-cdf5-4bc7-a947-47fc4420bf84.png)

**Comment by opera0001** [comment]
done
