### ISSUE TITLE
我的提交显示已经合并，为什么logo还是没更新，已经过去好几天了

### ISSUE THREAD

**Issue by Wofxks** [TP-Lab/tokens#842]
0x04b6fFe0829CA73bDaFFA8285ce167acd12D380c，这个是我的地址，麻烦管理大大看一下，谢谢

**Comment by Wofxks** [comment]
合约地址：0x04b6fFe0829CA73bDaFFA8285ce167acd12D380c，名称：mars

**Comment by Wofxks** [comment]
好几天没更新logo，我也不清楚为什么，显示已经合并

**Comment by zhujiayu03** [comment]
请提供您的Pull request链接以便查看。

**Comment by Wofxks** [comment]
https://github.com/TP-Lab/tokens/pull/540   这个就是我的链接

**Comment by Wofxks** [comment]
@zhujiayu03   麻烦您看一下 谢谢

**Comment by Wofxks** [comment]
https://github.com/TP-Lab/tokens/pull/540/commits/b72e261660169204c23e7d2840c0e572c2a32429

**Comment by Wofxks** [comment]
这个是已经验证完的链接https://github.com/TP-Lab/tokens/pull/540/commits/b72e261660169204c23e7d2840c0e572c2a32429
