### ISSUE TITLE
The logo has not been modified in time

### ISSUE THREAD

**Issue by TMtoken** [TP-Lab/tokens#8545]
Hello, sorry for not seeing your message and failing to modify the logo in time

**Comment by opera0001** [comment]
Please send the correct logo here and tell me the github order number where you submitted the logo and I'll handle it for you.

**Comment by TMtoken** [comment]
![logo](https://user-images.githubusercontent.com/114926508/200116548-b9ea6c58-11aa-4c8a-8de2-66be9768d4f5.png)
The order number is 8529，thanks!

**Comment by opera0001** [comment]
done
