### ISSUE TITLE
NLT Logo request

### ISSUE THREAD

**Issue by nltlogo** [TP-Lab/tokens#8565]
https://github.com/TP-Lab/tokens/pull/8548
The code has been opened, please review
![logo](https://user-images.githubusercontent.com/117509437/200353784-b611561f-b504-40d9-a5df-927160d62b84.png)

**Comment by bluewhalebwe** [comment]
The size of the image I uploaded does not conform to the rules. How can I upload it again.

**Comment by opera0001** [comment]
Please check the message of the 8548 order.
