### ISSUE TITLE
麻烦修改下LOGO图片，非常感谢！

### ISSUE THREAD

**Issue by CJZVIPE2** [TP-Lab/tokens#8571]
您好，我是财经钻CZ官方工作人员，因为CZ合约地址更换，麻烦在修改下ERC20代币CZ的LOGO图片，非常感谢！

财经钻CZ官网公告：
https://www.cjz.vip/303743812.html

去掉原来老合约的LOGO，CZ老合约地址是（ERC20）：
0xDCa8738CF677CD25f0aeE853982E4dbc70EF8ACd
 
然后在CZ新合约添加上这个LOGO，CZ新合约地址是（ERC20）：
0xe9e2fb149f23d7563d09eb58932052552b4889ea

CZ的 LOGO（ERC20）：
https://www.cjz.vip/bdueimg/php/upload/image/20221108/1667898179419925.png

麻烦您了！

财经钻CZ客服联系方式：
QQ：318059325   Telegram: cjzvipe   邮箱：cz@cjz.vip

**Comment by opera0001** [comment]
To modify the contract address, you need to provide the reason for the modification and the link of the new hash value.

**Comment by CJZVIPE2** [comment]
您好，CZ修改合约地址的原因：
旧币基本上都回收了，更换的原因是老合约地址的用户被ZG和WBF交易所侵吞了一点币。被这两个交易所侵吞的币我们补偿给用户。还有极少数没有兑换的，联系我们兑换即可。

这是官网公告：
财经钻CZ官网公告：
https://www.cjz.vip/303743812.html

ERC20合约地址：
https://cn.etherscan.com/token/0xe9e2fb149f23d7563d09eb58932052552b4889ea

**Comment by opera0001** [comment]
Thank you very much for your answer, but your application for changing the contract address needs to submit a new tpt hash value link, so you need to add it, thank you.
