### ISSUE TITLE
麻烦更换合约地址

### ISSUE THREAD

**Issue by morse001** [TP-Lab/tokens#8576]
您好：

我是Morse项目组，现在申请更换Morse项目的合约地址。

更换原因：项目发展，原来的智能合约不适合现在的实际情况，所以需要更换为支持新经济模型的智能合约。

新合约地址：0x77A2e1F08B2bbFd459D10231c6eDce01645337fd

非常感谢！

**Comment by opera0001** [comment]
What is the original order number you submitted? You need to explain the reason for changing to a new contract address. A link to the new hash value is required for the new contract address change.

**Comment by morse001** [comment]
Hi:

Thank you for your great help.

the original smart contract address:  https://bscscan.com/token/0xefd4562705477e99dcc07cd9bde7ac5459883f86

update reason: the original smart contract isn't fit for our business developement, we must adopt new smart contract to support our new business model.

new smart contract address: https://bscscan.com/token/0x77A2e1F08B2bbFd459D10231c6eDce01645337fd

Best Regards

**Comment by opera0001** [comment]
The old contract address logo has been removed. If you replace the new contract address, you need to submit a new TPT hash value link.

**Comment by morse001** [comment]
Hi:

Just you metioned I need submit a new TPT hash value link, Coule I submit that link in this issue? 

Best Regards.

**Comment by morse001** [comment]
Hi:

From your information, At now the old contract logo has been removed, but this logo isn't added to the new contract address because I have not submit a new TPT hash link, So I need submit a new TPT hash value link in this issue to add that logo to my new contract address. Right or not?

thank you very much.

Best Regards.

**Comment by morse001** [comment]
Hi:

New TPT tx hash link: https://bscscan.com/tx/0xf043dd4f0696cafa1cee005b1d68cc32a85788674cc86de30193fed585891ed1
New verify tx hash link: https://bscscan.com/tx/0xa283f1e8fe9fad4500c6c6bbe482c0922fedd8d91f2dcfe852337d24f83702ae

thank your for your great help

Best Regards

**Comment by opera0001** [comment]
It has been processed for you, thank you for your reply.
