### ISSUE TITLE
NLT Contract problem #8548

### ISSUE THREAD

**Issue by nltlogo** [TP-Lab/tokens#8581]
https://github.com/TP-Lab/tokens/pull/8548
I will not give up the ownership of the contract

**Comment by nltlogo** [comment]
hello,Can you help me deal with this problem?

**Comment by nltlogo** [comment]
Is there any problem that I need to solve?

**Comment by nltlogo** [comment]
> Hidden owner, we need to know what his purpose is and who his controllers are.

This is not to actively hide the owner, the purpose of this is only to facilitate the management of contract permissions, ROLE_ADMIN is responsible for authorizing the role, ROLE_CONFIG is responsible for setting parameters, and ROLE_ROBOT is responsible for the calculation and write-back of the off-chain part

![telegram-cloud-photo-size-5-6318961941682434940-y](https://user-images.githubusercontent.com/117509437/202434217-a8e1f426-e972-4c0f-a376-f97bf63b9b76.jpg)

**Comment by opera0001** [comment]
It has been processed.
