### ISSUE TITLE
UVC Modifies information

### ISSUE THREAD

**Issue by UVCxinxi** [TP-Lab/tokens#8600]
sorry,I have been waiting to miss this message, yes I provided the wrong transaction information, the correct hash link is as follows:https://bscscan.com/tx/0xcf23195bd8a987559fd6ce11d357bbea0826fbc8dee3665ee5d78b67b8ed71cf

BSC - UVC - 0x9154bf968d1949a2dfa4f691c4d36c4d12f231c5 - https://bscscan.com/tx/0xcf23195bd8a987559fd6ce11d357bbea0826fbc8dee3665ee5d78b67b8ed71cf

**Comment by opera0001** [comment]
Okay I got it.
