### ISSUE TITLE
麻烦去掉旧合约地址的LOGO图片，非常感谢！

### ISSUE THREAD

**Issue by CJZVIPE2** [TP-Lab/tokens#8646]
您好，我是财经钻CZ官方工作人员，因为CZ合约地址更换，麻烦去掉一下旧合约地址的LOGO图片，以避免用户误解，非常感谢！

财经钻CZ官网公告：
https://www.cjz.vip/303743812.html

去掉原来旧合约的LOGO图片，CZ旧合约地址是（ERC20）：
0xDCa8738CF677CD25f0aeE853982E4dbc70EF8ACd

CZ更新后的新合约地址（ERC20）：
0xe9e2fb149f23d7563d09eb58932052552b4889ea

更换合约地址的原因：
旧币基本上都回收了，更换的原因是老合约地址的用户被ZG和WBF交易所侵吞了一点币。被这两个交易所侵吞的币我们补偿给用户。还有极少数没有兑换的，联系我们兑换即可。

麻烦去掉一下旧合约地址的LOGO图片，以避免用户误解，麻烦您了！

**Comment by opera0001** [comment]
All have been processed, you check it out.
