### ISSUE TITLE
Request for restoration of token logo inclusion

### ISSUE THREAD

**Issue by witulcwvtliw** [TP-Lab/tokens#8697]
Our token contract address: 0xF49075181875A90293D305BA190Eea53757cFe81, was removed from the logo because the holder maliciously posted an ad in the TokenPocket Twitter platform, so a new donation hash was added in coordination with TokenPocket in order to restore the logo again display. We promise that this will not happen again.

Link.：https://bscscan.com/tx/0x84fd51df0ae33040260d026ef975529f40ef5857f234c816e160e060cafd0c1f

**Comment by opera0001** [comment]
Please be patient.
