### ISSUE TITLE
1、The existence of hidden owner permissions is detected, this part needs to be explained in detail.

### ISSUE THREAD

**Issue by MUSICALPLANET** [TP-Lab/tokens#8714]
1、The existence of hidden owner permissions is detected, this part needs to be explained in detail. 
2、The submitted logo is not 256x256 pixels, please adjust it.

_Originally posted by @opera0001 in https://github.com/TP-Lab/tokens/issues/8713#issuecomment-1336105172_

**Comment by opera0001** [comment]
We have received your feedback, please wait patiently for the review. Thank you.
