### ISSUE TITLE
Add KELE Logo And Info

### ISSUE THREAD

**Issue by tangtang99990973** [TP-Lab/tokens#8719]
I have replied to you 
代币是可以转移的，我们目前是在自己的swap上面交易，后续会考虑上其他swap
or
Tokens are transferable, we are currently trading on our own swap and will consider other swap in the future

**Comment by tangtang99990973** [comment]
#8719

**Comment by tangtang99990973** [comment]
#8682

**Comment by taiyuan168** [comment]
![Uploading mmexport1670460654883.png…]()

**Comment by taiyuan168** [comment]
[]() [仲裁系统，裁判员](https://ftmscan.com/address/0x70e9f95b5a22942576809ff7C558309d251b7c44)
