### ISSUE TITLE
显示已经合并，但是tp钱包仍然看不到图标

### ISSUE THREAD

**Issue by Wofxks** [TP-Lab/tokens#872]
https://github.com/TP-Lab/tokens/pull/540/commits/b72e261660169204c23e7d2840c0e572c2a32429
上面是已经合并的地址连接，名称是Mars，0x04b6ffe0829ca73bdaffa8285ce167acd12d380c合约地址，
请管理大大尽快处理下

**Comment by zhujiayu03** [comment]
请提交GitHub合并链接，以便查看。
