### ISSUE TITLE
0x70e9f95b5a22942576809ff7C558309d251b7c44

### ISSUE THREAD

**Issue by taiyuan168** [TP-Lab/tokens#8740]
![mmexport1670460654883](https://user-images.githubusercontent.com/120084186/206655577-cf83ca2c-9b40-4b56-820d-7c4eacf0aaca.png)
[ARB仲裁系统](https://ftmscan.com/address/0x70e9f95b5a22942576809ff7C558309d251b7c44)

**Comment by opera0001** [comment]
What is the order number of your historical submission?

**Comment by opera0001** [comment]
Please resubmit the content as required by the tutorial, as you submitted it incorrectly.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info
