### ISSUE TITLE
币安只能链

### ISSUE THREAD

**Issue by nace-L** [TP-Lab/tokens#8862]
币安智能链提交不了代币，直接返回failed @ignasliu 
<img width="1845" alt="微信图片_20230105180551" src="https://user-images.githubusercontent.com/87641858/210754479-d9335aca-28e8-4af3-8ea6-1606ca551784.png">

**Comment by opera0001** [comment]
May I ask what is the contract address of the token you submitted?You can try using token contract in TokenPocket to search for and add the token you need to see if this token can be displayed?

**Comment by nace-L** [comment]
I have submitted the token information through github, and now it has been merged into the master branch. It can be normally displayed on TPApp, thank you
