### ISSUE TITLE
0x023F2af9807057f5E6Ef03742fF40418E54f907f/logo.png

### ISSUE THREAD

**Issue by good0777** [TP-Lab/tokens#8989]
![0x023F2af9807057f5E6Ef03742fF40418E54f907f:logo](https://user-images.githubusercontent.com/123971002/218413858-46ccccdf-c7a9-4351-bea7-e3812240fed2.png)

重新提交logo，由于目前显示的偏小，所以重新提交logo.以做修正。

**Comment by opera0001** [comment]
Please send me the order number of the token you submitted, or the contract address of the token.thank you

**Comment by good0777** [comment]
https://bscscan.com/token/0x720b58ed741e488b64c23fe559d490dd8ae5c656

**Comment by good0777** [comment]
请看下是否是这样，0x720B58ED741E488b64C23fe559D490dD8AE5c656。
这个是我们的合约地址。

**Comment by good0777** [comment]
有个问题很奇怪，我们递交的logo图是按照要求的大图，但是出来的效果却偏小

**Comment by opera0001** [comment]
I've taken care of it for you.The requirement is 256x256 pixels, but if the content of the logo theme is too small, the actual display will be affected.

**Comment by good0777** [comment]
收到，且已看到效果，谢谢您的帮助
