### ISSUE TITLE
how to add  info message and show nft picture?

### ISSUE THREAD

**Issue by wanplan** [TP-Lab/tokens#8995]
## description info
we have made pull request, and the logo is OK 
but the "description" is not, could you help me to check out  my info.json?
my pull request is  https://github.com/TP-Lab/tokens/pull/8976
## NFT picture
and out nft picture is not shown, is there  any specific requirements about the picture display?

<img width="408" alt="image" src="https://user-images.githubusercontent.com/116449064/218601264-73e3eda7-9ef0-49d7-8307-cc80c6ddf8e7.png">

**Comment by opera0001** [comment]
The introduction of NFT has been added, the picture is not displayed, may I ask what is the picture storage link you use?Or can other wallets be displayed normally?

**Comment by opera0001** [comment]
This problem has been dealt with. There are some minor problems with data acquisition. Sorry, dear.
