### ISSUE TITLE
看下火币链这个合约可以上头像不

### ISSUE THREAD

**Issue by QTQT980** [TP-Lab/tokens#9017]
合约地址：0x86a48017e7e11c6d641e9157dffc677b81449d9b
您好，这个合约权限已经丢了，就是在火币链显示没有开源，咨询了很多人，说是火币链显示有问题，麻烦看看这个合约可以上头像不

**Comment by QTQT980** [comment]
我也是看了火币链上了头像的合约，看了有10个，其中好几个也是没有开源头像也上了

**Comment by QTQT980** [comment]
![e91ef10af63d2e5db4aa8a6020c82be](https://user-images.githubusercontent.com/125717632/220013147-6e092fba-7331-4ece-a479-bbe6c15f1e05.png)
点这里没有反应，没法进去开源

**Comment by opera0001** [comment]
Sorry, I don't have a good way to solve this problem, so for the convenience of checking open source information and performing some other operations in the future, I still suggest feedbacks to the HECO technical side and fixing this problem.
