### ISSUE TITLE
Our Project is merged, but the token is not able to be shown in Token Pocket APP #9145

### ISSUE THREAD

**Issue by Team-Publish-Bc** [TP-Lab/tokens#9180]
你好。我们发现就在以前的`Swit-cc #9144`[commit 98d3f45](https://github.com/TP-Lab/tokens/pull/9144)、`FIFAII #9143`[commit ea65c50](https://github.com/TP-Lab/tokens/pull/9143)和`NWISH #9141`[commit bdbeca5](https://github.com/TP-Lab/tokens/pull/9141) 等，这些都已在Token Pocket APP上被反应了。不过，我们的token仍然无法在应用程序中被看到. 所以，**我们想知道何时能看到`PUBLISH(NEWS)`的token在应用程序中**。谢谢。麻烦您了。

We noticed that previous commits such as Swit-cc #9144, FIFAII #9143, and NWISH #9141 have already been reflected on the Token Pocket app. However, our token still cannot be seen in the application. **Therefore, we would like to know when we can see the `PUBLISH(NEWS)` token in the app**.
![TokenPocketAppResult](https://user-images.githubusercontent.com/127287932/227405074-0735370c-3ebd-42c4-be41-c5668a2d6ed0.jpg)

_Originally posted by @RHIE-coder in https://github.com/TP-Lab/tokens/issues/9145#issuecomment-1475490106_

**Comment by opera0001** [comment]
![image](https://user-images.githubusercontent.com/99245006/227408142-4ba0f877-6d0d-4d56-9c28-37004d417e77.png)
The three tokens you mentioned can all be searched and loaded normally in the wallet, and their logos are also displayed correctly. Therefore, the best way to search for these tokens is to use their contract addresses when searching and adding them in the wallet. This will help you find the tokens quickly and accurately.

**Comment by Team-Publish-Bc** [comment]
谢谢很快的回答，辛亏您提供的信息，我们再仔细得看以后发现这应用程序具有换Blockchain Network功能。换了Network才可以看到我们的token了。
