### ISSUE TITLE
PR 9154 Audit report

### ISSUE THREAD

**Issue by GoldNeta** [TP-Lab/tokens#9181]
Hi, 
Here is the audit report from sharkteam.org
https://www.sharkteam.org/report/audit/20230323001C_en.pdf

This is regarding PR for GNT token info and logo:
https://github.com/TP-Lab/tokens/pull/9154

Please let us know if the token can be added to Token Pocket. Thanks

**Comment by opera0001** [comment]
Done

**Comment by GoldNeta** [comment]
Should I reopen the PR #9154 ? So it can be merged to master. Thanks
