### ISSUE TITLE
update  logo request

### ISSUE THREAD

**Issue by ccnamz** [TP-Lab/tokens#9298]
This is a request that I have already merged,  https://github.com/TP-Lab/tokens/pull/9248

My logo size is not very suitable. I hope it can be modified

**Comment by ccnamz** [comment]
![logo](https://user-images.githubusercontent.com/130300293/234481571-c9091e50-1084-40e3-ada4-a68381e97c85.png)

**Comment by ccnamz** [comment]
this is new  logo

**Comment by opera0001** [comment]
Done
