### ISSUE TITLE
关于 TAPDAO 添加logo 失败 #9315

### ISSUE THREAD

**Issue by TAPDAO952** [TP-Lab/tokens#9329]
项目一直正常运行中，也可以正常交易，是有什么其他问题吗，目前项目在开发游戏，等游戏开发好后会丢掉权限。

**Comment by TAPDAO952** [comment]
#9315

**Comment by opera0001** [comment]
![image](https://user-images.githubusercontent.com/99245006/236590473-58fbe30c-3fe6-41f6-8e98-54b2090c167b.png)
Dear, this has already been recorded, not closed. Please take a look again.
