### ISSUE TITLE
update logo

### ISSUE THREAD

**Issue by nace-L** [TP-Lab/tokens#9380]
Hello, I need your help to update the logo for this https://github.com/TP-Lab/tokens/pull/8863
![UNC](https://github.com/TP-Lab/tokens/assets/87641858/22d9efbd-f146-405e-9346-c335b06a70b5)

**Comment by nace-L** [comment]
@opera0001 Could you help me replace the logo? Or can you tell me how to replace it, please

**Comment by opera0001** [comment]
Your application has been successfully deployed. Please check the token list for more information.
