### ISSUE TITLE
The explanation of the addition of FIST logo and info 

### ISSUE THREAD

**Issue by cunduoshao** [TP-Lab/tokens#9392]
Hello. I am so sorry not to reply your message in time. Our FIST logo does have a lot of common with the exiting FIST logo. But there is a difference. The left and right arcs of our logo are unbroken, while the exiting logo is broken symmetrically. Please check it. Thank you.
Pull request #9374 
![3E19FB89-2D29-4F62-8230-8AB4BB316954](https://github.com/TP-Lab/tokens/assets/90882930/16d0394b-334b-455b-a5e9-1043391695d3)

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/f7abe80b-e4f3-4531-96a4-6af19ac4a6cd)
In my opinion, the difference here is not significant, so I would still suggest making some modifications to make them appear more distinct. Thank you.

**Comment by cunduoshao** [comment]
![267BBB26-5180-4743-B7BA-47AD8E625338](https://github.com/TP-Lab/tokens/assets/90882930/4cba47f2-b4d3-4f14-b770-5892b95de270)
Hello. Can this one work？
