### ISSUE TITLE
0x460143eccdFF61890B20BF8A6B0e7eaF65C2E94a

### ISSUE THREAD

**Issue by alw123456** [TP-Lab/tokens#944]
{
“名称”： “Tokamak Network”，
“网站”： “ - ”，
“描述”： “Tokamak Network”，
“资源管理器”： “ https://hecoinfo.com/token/0x460143eccdFF61890B20BF8A6B0e7eaF65C2E94a ”，
“类型”： “ HRC-20”，
“符号”：“TON”，
“小数”：18，
“状态”：“活动”，
“id”：“0x460143eccdFF61890B20BF8A6B0e7eaF65C2E94a”
}
![D919x5-s_400x400](https://user-images.githubusercontent.com/84399291/124291096-c741a200-db86-11eb-991c-a9c8179c2420.png)

**Comment by zhujiayu03** [comment]
请提交至Pull requests
