### ISSUE TITLE
TTM LOGO Do not show

### ISSUE THREAD

**Issue by 1airdrop** [TP-Lab/tokens#9442]
https://github.com/TP-Lab/tokens/pull/9420

**Comment by 1airdrop** [comment]
Please check the problem that the wallet does not display the LOGO
TTM
BEP20
0xaaA8e19E6C4A3355A1804E8731328978C3d6B85f

**Comment by 1airdrop** [comment]
@opera0001

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/2793b5eb-499f-48ae-ae8d-2677f9d14428)

I'm sorry, dear. I think there might have been an error during the upload of the logo to the server. I apologize for the inconvenience.
