### ISSUE TITLE
add qwasp logo file #9451

### ISSUE THREAD

**Issue by qwasp-token** [TP-Lab/tokens#9458]
The contract has passed the security audit of Armors

**Comment by opera0001** [comment]
Please provide the link for security audit. Thank you.

**Comment by qwasp-token** [comment]
https://q.wasp-token.com/static/img/token_audit.pdf

**Comment by qwasp-token** [comment]
do I need to resubmit ？

**Comment by opera0001** [comment]
The merger has been completed.
