### ISSUE TITLE
请问我能修改已合并LOGO的项目描述吗

### ISSUE THREAD

**Issue by ConLogo** [TP-Lab/tokens#9465]
这是之前TPT的转账记录
https://bscscan.com/tx/0x7b566e6f8d11b98744419a4ffddd95b088494770cabd51a382c52fef57c64bbe
我想要修改项目的描述（description），
{
    "name": "CON",
    "website": "https://bscscan.com/token/0x0Eb455A49bF180DEd02732b9Aa52A3B7C1146A8D#code",
    "description": "火星盾是全球性且宇宙性的，倡导虚实结合，是第六代数字货币第一个币",
    "explorer": "https://bscscan.com/token/0x0Eb455A49bF180DEd02732b9Aa52A3B7C1146A8D",
    "type": "BEP20",
    "symbol": "CON",
    "decimals": 18,
    "status": "active",
    "id": "0x0Eb455A49bF180DEd02732b9Aa52A3B7C1146A8D"
}

**Comment by opera0001** [comment]
This token has already been listed, so the JSON content does not need to be modified.

**Comment by ConLogo** [comment]
What do I need to do if I want to modify the description? Where will the description be displayed?

**Comment by ConLogo** [comment]
> This token has already been listed, so the JSON content does not need to be modified.

What do I need to do if I want to modify the description? Where will the description be displayed?
