### ISSUE TITLE
Does zksync work already

### ISSUE THREAD

**Issue by MingHuiLiu** [TP-Lab/tokens#9470]
Hello everyone, can the zksync chain now accept erc20 and erc721 icon modification, and whether it can be displayed normally after the submission is passed?
@opera0001

**Comment by opera0001** [comment]
TokenPocket supports the zksync Erc public chain, so both regular tokens and NFTs on this chain are supported. Starting today, we also support token price display on this chain. However, this requires the liquidity pool of the tokens to reach a certain amount before it can be displayed correctly.

Therefore, if there are any submission requirements for similar token logos, feel free to submit them.
