### ISSUE TITLE
Token listing (Pull Request #9461)

### ISSUE THREAD

**Issue by web3-anon** [TP-Lab/tokens#9477]
#9461 was closed due to insufficient explanation w.r.t. the contract's hidden owner-related functionality. @opera0001 wanted to have details related to audit certification.

All the contracts' audits related to OX are due soon (within 1-2 months); right now the focus is on bridging OX to Arbitrum/BSC/Polygon, bringing voteOX to L2s, etc.

So I'd like to ask if there's any possibility of provisional listing for ~1-2 months, till the time of our audit?

**Comment by opera0001** [comment]
I'm sorry, dear, but we can't control the risks, so we can't help you with the process. Therefore, you can only display the logo normally after completing the audit and proving its safety.
