### ISSUE TITLE
0xeDAE239cFc8513a28fE5A8E2Cf9683608ff6C86B 更换logo申请

### ISSUE THREAD

**Issue by BTC8888BTC** [TP-Lab/tokens#9497]
你好logo已经上了，现在需要更换logo。合约地址：0xeDAE239cFc8513a28fE5A8E2Cf9683608ff6C86B

**Comment by BTC8888BTC** [comment]
更换是要重新提交，转账5万个tpt 还是要怎么换，
![logo](https://github.com/TP-Lab/tokens/assets/137019958/3b3fd32a-ea0f-4cad-9e80-a9a8d0566614)

**Comment by BTC8888BTC** [comment]
上面是新的logo，麻烦给与通过谢谢

**Comment by opera0001** [comment]
The logo replacement has been completed.
