### ISSUE TITLE
 更换logo申请

### ISSUE THREAD

**Issue by WIFI8888** [TP-Lab/tokens#9503]
你好logo已经上了，现在需要更换logo。合约地址：0xeDAE239cFc8513a28fE5A8E2Cf9683608ff6C86B
更换是要重新提交，转账5万个tpt 还是要怎么换，
![image](https://github.com/TP-Lab/tokens/assets/137374344/e87447f4-c89f-4b48-81bc-477f140e708c)

**Comment by opera0001** [comment]
The logo replacement has been completed.
