### ISSUE TITLE
显示“已验视”但是TP钱包还是不显示LOGO 请帮忙看看是不是提交的资料有误还是什么呢？？？谢谢

### ISSUE THREAD

**Issue by Wofxks** [TP-Lab/tokens#952]
代币名称：Mars

链：BSC链
合约地址：0x04b6fFe0829CA73bDaFFA8285ce167acd12D380c
合并链接：Add Mars logo and info   https://github.com/TP-Lab/tokens/pull/540

**Comment by Bow0628** [comment]
@Wofxks #947 
Duplicate of #

> ``

**Comment by Wofxks** [comment]
> @Wofxks #947
> #的副本
> 
> > ``

你吗没了？  你为什么在我下面回复  ？  自己没长手？

**Comment by zhujiayu03** [comment]
请刷新后再次查看。
