### ISSUE TITLE
Is it possible to refund TPT that was sent to the wrong address?

### ISSUE THREAD

**Issue by ccoffice** [TP-Lab/tokens#9553]
During the application process to list a token on TP Wallet, due to an error, TPT that was originally supposed to be transferred to 0x7837AE9E4FD6E967F1B8C8824D6288ECE6e730F9, was mistakenly sent to address 0xECa41281c24451168a37211F0bc2b8645AF45092. Is it possible to have them returned?

@opera0001

**Comment by opera0001** [comment]
I'm sorry, but once the transfer of assets on the blockchain is complete, it cannot be changed. Therefore, I regret that I cannot assist you.
