### ISSUE TITLE
token submit dapp

### ISSUE THREAD

**Issue by babyface001** [TP-Lab/tokens#9594]
can we do this process with dapp,

transfer token and emit a submit event

```
function submit(uint chain_id, string symbol, address token){
    tpt.transferFrom(msg.sender, address(this), amount);
    emit Submit(chain_id, symbol, token);
}
```

fill a form, and download info json, then call `submit` to verify.
no one wants to build the long transaction data.

**Comment by babyface001** [comment]
@opera0001  write a contract to submit and verify transaction.

nobody want to build a raw transaction data 'BSC - XXX - 0xdddd - hash'

**Comment by opera0001** [comment]
The operations are absolutely no problem for technicians, and it is also a very rigorous verification process. So please follow this procedure for the operations. Thank you.
