### ISSUE TITLE
Replace the logo of AMCEP NFT and the display logic of NFT in the wallet，Contract: 0x7e6a89971b826cBa83E29CFbE638813eff5D185D

### ISSUE THREAD

**Issue by AIMetaClub** [TP-Lab/tokens#9596]
Dear TP administrator,
1. We are the publisher of the NFT contract 0x7e6a89971B826CBA83E29CFBE638813Eff5d185D. We have previously submitted the needs of LOGO and NFT in TP Wallet. At the same time, we have been confirmed. 

2. Due to the previous logo icon design color problem, the display in the TP Wallet is not clear. In order to better serve the user, we hope to mention it. The new logo is replaced by replacing the original logo, I hope to get your support, thank you.
Below is the new Logo icon.
![logo](https://github.com/TP-Lab/tokens/assets/118162660/11688d2a-f518-490d-84b6-814308e25c83)

3. In addition, our NFT is still being Mint, our NFT also hopes to be displayed in the TP wallet. The specific display rules are(If need a gif image link, please use the link on Github directly, thank you very much.):
a. Users numbered 1-6000 show purple pictures
![purple_1](https://github.com/TP-Lab/tokens/assets/118162660/3f25e6dc-fdc4-46db-bbfa-e2201f1a547d)
b. Users with numbers 6001-20000 display orange pictures
![orange](https://github.com/TP-Lab/tokens/assets/118162660/d0b7e3aa-12d2-49e4-9d9f-126f2eff149a)
c. Users with numbers 20001-50000 display green pictures
![green](https://github.com/TP-Lab/tokens/assets/118162660/00a91ddd-ab4b-43db-bb3e-ce9a2de74d62)
d. Users with numbers 50001-100000 display blue pictures
![blue](https://github.com/TP-Lab/tokens/assets/118162660/0563f583-a6d8-467a-a196-02ca705cbd9c)
e. Numbers above 10000 are displayed in white
![white](https://github.com/TP-Lab/tokens/assets/118162660/6257b360-5b3b-432f-a3b9-a6ddbc4d015f)

4. The following is our NFT contract source code:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract AMCEP721 is ERC721Enumerable, Ownable {

    string public baseURI;

    mapping(address => bool) public minters;
    
    constructor() ERC721("AMC Entry Pass", "AMCEP") {}


    function addMinter(address minter) public onlyOwner {
        minters[minter] = true;
    }

    function removeMinter(address minter) public onlyOwner {
        minters[minter] = false;
    }


    function mint(address toAddress, uint256 tokenId) external{        
        require(verifyUser(msg.sender), "No permissions!");
        _safeMint(toAddress, tokenId);
    }

    
    function verifyUser(address user) public view returns(bool) {
        return user == owner() || minters[user];
    }


    // internal
    function _baseURI() internal view virtual override returns (string memory) {
        return baseURI;
    }


    function setBaseURI(string memory _newBaseURI) external onlyOwner {
        baseURI = _newBaseURI;
    }


    function burn(uint256 tokenId) external {
        require(ownerOf(tokenId) == msg.sender, "You do not own this token");
        _burn(tokenId);

    }
    

    function tokensOfOwner(address owner) external view returns(uint256[] memory){
        uint256 balance = balanceOf(owner);
        uint256[] memory tokens = new uint256[](balance);
        for (uint256 i = 0; i < balance; i++) {
            tokens[i] = tokenOfOwnerByIndex(owner, i);
        }
        return tokens;
    }

}
```

**Comment by opera0001** [comment]
The logo for the address 0x7e6a89971b826cBa83E29CFbE638813eff5D185D has now been updated with the provided image. However, when it comes to displaying NFTs, we are unable to make adjustments; typically, the necessary configurations should be handled by your end. We can only fetch the content from the default links.
