### ISSUE TITLE
update logo for Ex30

### ISSUE THREAD

**Issue by babyface001** [TP-Lab/tokens#9627]
token address:
```
0x6Ae1ad4444c2D4772F7E4f25428F070df9486572
```
![logo](https://github.com/TP-Lab/tokens/assets/34022395/cb74815c-df1a-4187-8281-db11285f27a2)

**Comment by opera0001** [comment]
What is the contract address of this public blockchain? Is it a regular token or an NFT? The submitted format is not 256x256 pixels; please provide the order number of this token's submission history on GitHub.

**Comment by babyface001** [comment]
chain: polygon
type: ERC20
contract address: 0x6Ae1ad4444c2D4772F7E4f25428F070df9486572
submission history: https://github.com/TP-Lab/tokens/pull/9595
![logo](https://github.com/TP-Lab/tokens/assets/34022395/b90c20c7-3a47-4afe-8f8a-bc5d2f59d2dd)

**Comment by opera0001** [comment]
The logo replacement has been completed, and the new logo is indeed more eye-catching than the old one.
