### ISSUE TITLE
关于PR #9649

### ISSUE THREAD

**Issue by CODCoin1** [TP-Lab/tokens#9664]
贵方拒绝的理由是token存在风险（无法sell），我也用TokenScurity监测了一下，确实显示卖出税率100%，但是这个完全是误判了，从token的交易记录和源码可以看出，sell完全没有问题。
token交易记录4,230COD to 1.46BSC-USD
https://bscscan.com/tx/0x7a403b181f6d71dbca84233e2531f5be02d55cdcc404c6234eb35126423067e4
下面是pancakeswap的截图。
![image](https://github.com/TP-Lab/tokens/assets/141609122/aed4f0e0-9a33-43b2-a367-058b8178e403)

**Comment by opera0001** [comment]
A portion of the code implemented a rather "foolish" feature, resulting in outcomes flagged as unsellable by the tool's detection. However, I have already reached out to the Go+ detection team to rectify the data. Please take a look.
