### ISSUE TITLE
您好 0xA78e888599747389deA47C2C106e47F2853BB005 更换lOGO 和简介申请

### ISSUE THREAD

**Issue by DNB8888** [TP-Lab/tokens#9676]
您好 火币链（heco）   ZOL头像和简介已经上了，现在申请更换logo和  简介，如果简介更换不了，麻烦给与去除谢谢。
合约地址：0xA78e888599747389deA47C2C106e47F2853BB005
新logo：
![logo](https://github.com/TP-Lab/tokens/assets/142000181/ec4bab1e-c84b-44ed-88d7-88aac854e17b)
新简介：AOI是新一代去中心化AI算力网络，解决现有AI算力高成本、数据隐私问题，旨在推动大模型轻量化、本地化部署，提高数据隐私性，推动AI大规模采用。

如果简介更换不了，麻烦给与去除谢谢。

**Comment by opera0001** [comment]
The introduction content has been cleared, but if you need to change the logo, you will need to submit a new GitHub order and proceed with the TPT donation process again.

**Comment by MIMIC88888MIMIC** [comment]
您好，我经常进行捐赠TPT的， 这个项目的TPT已经捐赠过了，麻烦给予更改头像谢谢。原来更改头像都没有让捐赠过。这个项目的池子确实没有多少钱。麻烦给予通过谢谢您！

**Comment by HXRB8888** [comment]
您好，麻烦给予通过，我经常进行捐赠TPT的，这是我的地址可以查看捐赠次数 ,
这个项目的TPT已经转让过了，麻烦给予更改头像谢谢。原来更改头像都没有让转让过。这个项目的池子确实没有多少钱。麻烦给予通过谢谢！
BSC: 
 0x21063da5434d728163107D7239A52BcF2fD06300
