### ISSUE TITLE
0xA78e888599747389deA47C2C106e47F2853BB005 申请LOGO 更改麻烦给予通过

### ISSUE THREAD

**Issue by MIMIC88888MIMIC** [TP-Lab/tokens#9688]
您好火币链（heco）ZOL头像已经上了，现在申请更换头像，麻烦给与得谢谢。 
合约地址：0xA78e888599747389deA47C2C106e47F2853BB005
![logo](https://github.com/TP-Lab/tokens/assets/142665065/e8fc3d52-2eb4-42c2-85d7-ce0e0f9b0ed6)
我经常上头像的，原来都是给免费更改的，麻烦这次给予通过，谢谢！

**Comment by opera0001** [comment]
Unless the logo change request is submitted within one week on GitHub, it will not be processed. Sorry.
