### ISSUE TITLE
申诉订单 #9811   

### ISSUE THREAD

**Issue by CryptoPanda6** [TP-Lab/tokens#9821]
#9811 是一个申请logo的订单，该订单被拒绝，原因是：合约内有隐藏权限。

针对该问题，不明白的是：哪个地址因为具体哪个方法被视为隐藏的权限？仅仅是因为营销钱包可以提取合约内代币？这是为了维护池子交易稳定的功能，之前已经做了解释。

此外，TP钱包的检测采用的是GoPlus的接口，那么为什么GoPlus没有检测出这个功能？如果不相信GoPlus的检测，TP又为什么使用人家的接口？这样的话，检测结果的意义在哪里呢？不止是GoPlus，cyberscope的审计检测同样没有列出相关风险（相关检测见截图）

当然，并不是说检测结果就一定准确，只是作为重要参考来说，既然两家不同检测方法检测的结果都没问题，到底问题出在哪里，而不给上logo？

![cyberscope检测](https://github.com/TP-Lab/tokens/assets/84281098/eef86754-f1dc-4669-854e-83e98c4b7a67)
![GoPlus检测截图](https://github.com/TP-Lab/tokens/assets/84281098/8ce17ffb-1bd3-40f5-8972-8e72675e80b2)

**Comment by CryptoPanda6** [comment]
TP的检测结果也是如此，没有说这个合约有隐藏权限，具体见下图：
![TP检测截图](https://github.com/TP-Lab/tokens/assets/84281098/0f4899f1-7470-410a-bca4-0d80c49c4a70)

**Comment by opera0001** [comment]
https://gopluslabs.io/token-security/56/0x5B5387D9123D01D04B7BA39f5B42019Ea3e90246

The token at 0x5B5387D9123D01D04B7BA39f5B42019Ea3e90246 has been inspected, and we have provided feedback to the go+ technical team. However, it is confirmed that there is indeed a hidden owner's entry point, and go+ is capable of detecting this prompt successfully. You can take a look for yourself.
