### ISSUE TITLE
#9809 您好，这个订单头像怎么没有上去， 也没有说问题

### ISSUE THREAD

**Issue by DNBSjvkar1** [TP-Lab/tokens#9822]
您好，#9809这个头像提交了好几天了，怎么突然关闭了，头像也没上去
![c6635a6e20efb248da7ba5d991ec8eb](https://github.com/TP-Lab/tokens/assets/144655107/165d3743-d9a6-46cd-a1ae-d5cb136bc333)

合约：0xe1BDA6faeAFfA6b8BF1F64Ad2E7FddE4aDA1AEAa
简介：Zhiyuan Chain BTF is committed to exploring the combination of district chain and artificial intelligence, and providing a neutral, non-interest biased, open and trusted platform main chain for blockchain world builders and value concept identitarians.
官网：https://site.vrbqrcg.cn/
![logo](https://github.com/TP-Lab/tokens/assets/144655107/79fe230a-728a-4fc0-81ee-154a9f685651)

**Comment by opera0001** [comment]
Dear, this has already been reviewed, and all that's left is for you to patiently wait. Typically, the recording process will be completed within 2 days.
