### ISSUE TITLE
Request to resume logo submission.  #9476

### ISSUE THREAD

**Issue by pintoken** [TP-Lab/tokens#9857]
Request to resume logo submission. Owner permissions have been discarded. And passed the ave.ai platform security audit
It is also verified by coingecko and coinmarketcap

https://ave.ai/token/0xb86126b872e3f23bc62d6a4a3152ec65202a2073-bsc?from=Default

https://www.coingecko.com/en/coins/pin-token

https://coinmarketcap.com/currencies/pin-token/

#9476

**Comment by opera0001** [comment]
Done
