### ISSUE TITLE
How to update token social link information

### ISSUE THREAD

**Issue by pintoken** [TP-Lab/tokens#9866]
I need to add my token's social media link, but I can't find my token folder in the warehouse, how do I update the information?
The token information was added three days ago #9857

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/3b6e3863-4df1-4cdb-9b87-f9ff7721ea3f)

The logo of this token is already displaying correctly in TokenPocket. Is there anything else you need me to help you with now?

**Comment by pintoken** [comment]
> ![图像](https://user-images.githubusercontent.com/99245006/274648344-3b6e3863-4df1-4cdb-9b87-f9ff7721ea3f.png)
> 
> 该代币的徽标已在 TokenPocket 中正确显示。现在还有什么需要我帮你的吗？

Link this column inside the information I should add it, because previously there is a display link here. But not anymore. Just like the USDT link
<img width="331" alt="links" src="https://github.com/TP-Lab/tokens/assets/118411489/8b01ea02-bf08-4866-a557-514dceb848ff">
![Uploading links1.png…]()

**Comment by pintoken** [comment]
> ![image](https://user-images.githubusercontent.com/99245006/274648344-3b6e3863-4df1-4cdb-9b87-f9ff7721ea3f.png)
> 
> The logo of this token is already displaying correctly in TokenPocket. Is there anything else you need me to help you with now?

Links this column inside the information I should add it, because previously there is a display link here. But not anymore. Just like the USDT links
<img width="331" alt="links" src="https://github.com/TP-Lab/tokens/assets/118411489/bb514aa6-4942-4fd9-bd3e-84f00636db9b">
<img width="331" alt="links1" src="https://github.com/TP-Lab/tokens/assets/118411489/6cffbd31-b12d-4bf2-a088-2adad69fcc0b">

**Comment by opera0001** [comment]
The official website has already been updated for you. Typically, we do not provide these services, and other contact methods are temporarily not listed. We apologize for any inconvenience.

**Comment by pintoken** [comment]
> The official website has already been updated for you. Typically, we do not provide these services, and other contact methods are temporarily not listed. We apologize for any inconvenience.

I have seen the information of other tokens in the TP wallet, and their tokens also show the information of Twitter and Telegram, what can I do to add these information?
