### ISSUE TITLE
代币logo申述#9884 

### ISSUE THREAD

**Issue by cc232295** [TP-Lab/tokens#9889]
于#9884 已经提交了上传代币logo的PR，但是回复代币合约有隐藏权限。

该合约所有权以及隐藏权属者皆已抛弃并通过ave.ai审查。
ave:
https://ave.ai/token/0x1d65cb57efb96c674aede0c3423d41fc6fb76fe7-bsc?from=Default

抛弃owner的hash：https://bscscan.com/tx/0xa4fc411fe6a430096e77293524c33f234a86d9730ec3c11a58b4602ba138253f
抛弃隐藏owner的hash：https://bscscan.com/tx/0x745c065c47cdf0e799124296062e93419aebbbfdf6b8af90646ead03a05c2f12

**Comment by opera0001** [comment]
Sure, I will review the contract address again. Thank you for your feedback.
