### ISSUE TITLE
add TRGC logo and info #9870 update logo, How to resubmit?

### ISSUE THREAD

**Issue by Leo900805** [TP-Lab/tokens#9892]
before 
-----------------------
The token control permissions have not been discarded and still retain the ability to modify transaction fees, suspend token trading, and other permissions. Please provide an explanation of the functionality of these features.

The submitted logo is not 256x256 pixels, please make the necessary adjustments."
----------------------
Sorry I just saw it!
How to I resubmit logo?

**Comment by opera0001** [comment]
What is the order number you submitted? You can send me the correct format logo in the submitted order.

**Comment by Leo900805** [comment]
I haven't submit, How to do? Can you any guide?

**Comment by opera0001** [comment]
So, can you tell me your order number that you submitted, and you can also send the logo here.

**Comment by Leo900805** [comment]
before I submit "add TRGC logo and info #9870"

**Comment by Leo900805** [comment]
later I adjust the logo I sent here to you

**Comment by opera0001** [comment]
Done

**Comment by Leo900805** [comment]
?Done?

**Comment by opera0001** [comment]
I have already processed it, you can check the tokens now.

**Comment by Leo900805** [comment]
How we can check?

**Comment by opera0001** [comment]
![image](https://github.com/TP-Lab/tokens/assets/99245006/23152d83-cc03-43fa-93ab-24b1a0099a9a)

**Comment by Leo900805** [comment]
ok nice！thank you so much
