### ISSUE TITLE
Token Logo Submitted and Approved, but Not Displaying Properly

### ISSUE THREAD

**Issue by jianme** [TP-Lab/tokens#9938]
Greetings! I have submitted token logos on the TP platform multiple times. However, I recently encountered an issue. Although my code has been synchronized to the TP repository on GitHub, the logos for the following two tokens are not displaying in the TP wallet. I would appreciate your assistance in investigating this matter.

Here are the two tokens on BSC and their respective contract addresses:

PANDA: 0x62cfe8ac265918815f3ad5a2546d0dd96c62789b
BDD: 0x589a2bf2b338dd9ca228a142fb88c38c732df2a2

Thank you very much for your help and support. I look forward to hearing from you.

**Comment by opera0001** [comment]
Please provide the logos for these two tokens after their submission on GitHub, as I couldn't find any submission records for these tokens on GitHub. Another possibility is that your GitHub account has been banned by the official GitHub authorities.

**Comment by jianme** [comment]
Why? I can open and see the logo

BDD: https://github.com/TP-Lab/tokens/blob/master/bsc/0x589a2bf2b338dd9ca228a142fb88c38c732df2a2/logo.png

PANDA: https://github.com/TP-Lab/tokens/blob/master/bsc/0x62cfe8ac265918815f3ad5a2546d0dd96c62789b/logo.png

**Comment by jianme** [comment]
Can you deal with it?

**Comment by opera0001** [comment]
Dear [Name], please review our submission tutorial and follow the instructions to submit to the specified directory. The directory you submitted to is incorrect; please double-check.

**Comment by opera0001** [comment]
CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by jianme** [comment]
Because I have submitted it many times, and it has always been submitted in this way. So the directory I submitted now is incorrect, what should I do now? Can you please help me with this.

**Comment by jianme** [comment]
Can you directly help me switch to the correct directory? I will be more cautious next time.

**Comment by jianme** [comment]
There is nothing wrong. The directory I submitted is:

PANDA： https://github.com/TP-Lab/tokens/tree/master/bsc/0x62cfe8ac265918815f3ad5a2546d0dd96c62789b
BDD：https://github.com/TP-Lab/tokens/tree/master/bsc/0x589a2bf2b338dd9ca228a142fb88c38c732df2a2

But when I click on the specific file, such as: 
https://github.com/TP-Lab/tokens/tree/master/bsc/0x62cfe8ac265918815f3ad5a2546d0dd96c62789b. 
The directory will be redirected to: 
https://github.com/TP-Lab/tokens/blob/master/bsc/0x589a2bf2b338dd9ca228a142fb88c38c732df2a2/logo.png

So the directory I submitted is correct. Could it be a management issue with the TP wallet github repository?

**Comment by opera0001** [comment]
I'm sorry, but you can only submit this data yourself. Please have your technical team handle the process.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

**Comment by jianme** [comment]
Resubmit? Why do I need to resubmit? What was wrong with my previous submission?  the method I submitted earlier was based on your tutorial.

**Comment by jianme** [comment]
Can you give me a clear answer? The method I submitted before was fine, but why can’t it be displayed? Can you answer seriously?

**Comment by jianme** [comment]
All the information was submitted by me, and I am the technical person in charge. Can you give me a clear reply?

**Comment by jianme** [comment]
我现在最困惑的是，我都已经按照正确方式提交了为什么显示不了，我如何才能让我token的logo显示。我需要再次提交？可我代码都同步过去了啊，这又有什么必要（因为都通步过去了就不需要再提交了啊）。

能不能负责任些，给个清晰的解释，哪怕是给钱包地址我直接给你打钱帮我处理也行啊。一直按照你们的方式提交，提交了显示不了也不说个所以然出来，我真的觉得你们好不负责任。一个简单问题，非要弄那么久，效率是真的低。

希望您能明白我的意思与困惑，并给个清晰的答复，让我好处理可以吗，求你了，我就是技术，写了十多年的代码，没见你们这样的。

**Comment by jianme** [comment]
我真的提交方式就是按照文档来的，目录也是跟别人的在一块的。真情求你，为什么显示不了，能不能给个清晰的解释？

**Comment by opera0001** [comment]
CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info

Please follow the instructions in the tutorial carefully when submitting.
