### ISSUE TITLE
BNB Whales token submission

### ISSUE THREAD

**Issue by BNBWhales** [TP-Lab/tokens#9948]
i have filled all the required fields from the Submit new token page, and i uploaded all the data to GitHub, but it keeps giving Failed error. can you guide me for a correct token submission.

**Comment by opera0001** [comment]
Please follow the official guidance and tutorial to submit the logo.

CN：https://tphelp.gitbook.io/cn/wallet-operation/submit-token
EN：https://help.tokenpocket.pro/en/developer/how-to-submit-a-token-logo#steps-of-adding-a-token-logo-info
