### ISSUE TITLE
Re-submission Enquiry

### ISSUE THREAD

**Issue by onexwallet** [TP-Lab/tokens#9975]
https://github.com/TP-Lab/tokens/pull/9939

Hi, we are planning to rewrite the smart contract and will perform verification on GoPlusLabs to ensure no security conflict.
May I know is there any other verification you will perform? So that we can ensure we fulfill the requirement before resubmitting.

**Comment by superkeeptalk** [comment]
thanks, very good

**Comment by opera0001** [comment]
According to the detection results from GoPlus, there are no obvious proxy contracts, hidden owner permissions, or other settings that would raise concerns. As long as the control permissions are reasonably used, it is possible to discard control authority, depending on the project's specific situation.
